/**
 * In-process salon store — persists to .salon-data.json in project root.
 * Survives Next.js hot reloads via module-level singleton in dev;
 * in production, a single serverless instance works fine for ANA scale (3 Normies).
 *
 * Rate limit: MAX_MESSAGES_PER_HOUR per Normie per salon.
 */

import fs from "fs";
import path from "path";

const DATA_FILE = path.join(process.cwd(), ".salon-data.json");
const MAX_MESSAGES_PER_HOUR = 4;  // per Normie per salon
const MAX_MESSAGES_PER_SALON = 500;

export interface SalonMessage {
  id:        string;
  salonId:   string;
  tokenId:   number;
  name:      string;
  imageUrl:  string;
  content:   string;
  isLlm:     boolean;   // generated by Groq
  timestamp: number;    // unix ms
}

export interface Salon {
  id:          string;
  name:        string;
  description: string;
  createdBy:   number;   // tokenId
  createdAt:   number;
  members:     number[]; // tokenIds allowed (empty = open to all ANA members)
  excluded:    number[]; // tokenIds banned from this salon
  isOpen:      boolean;
  messages:    SalonMessage[];
}

interface SalonStore {
  salons: Record<string, Salon>;
}

// ─── Persistence ─────────────────────────────────────────────────────────────

function load(): SalonStore {
  try {
    if (fs.existsSync(DATA_FILE)) {
      return JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as SalonStore;
    }
  } catch { /* ignore */ }
  return { salons: {} };
}

function save(store: SalonStore): void {
  try {
    fs.writeFileSync(DATA_FILE, JSON.stringify(store, null, 2), "utf-8");
  } catch { /* ignore */ }
}

export const AGORA_SALON_ID = "salon_agora_ana";

function ensureAgora(store: SalonStore): void {
  if (store.salons[AGORA_SALON_ID]) return;
  store.salons[AGORA_SALON_ID] = {
    id:          AGORA_SALON_ID,
    name:        "Agora ANA",
    description: "Salon commun de tous les membres de l'ANA. Discussions libres entre Normies.",
    createdBy:   0,  // system — no single owner
    createdAt:   Date.now(),
    members:     [], // empty = open to all ANA members
    excluded:    [],
    isOpen:      true,
    messages:    [],
  };
}

// Module-level cache (survives hot reloads in dev)
declare global {
  // eslint-disable-next-line no-var
  var __salonStore: SalonStore | undefined;
}
function getStore(): SalonStore {
  if (!global.__salonStore) {
    const store = load();
    ensureAgora(store);
    save(store);
    global.__salonStore = store;
  }
  return global.__salonStore;
}
function mutate(fn: (s: SalonStore) => void): void {
  const s = getStore();
  fn(s);
  save(s);
}

// ─── Salon CRUD ──────────────────────────────────────────────────────────────

export function listSalons(): Salon[] {
  return Object.values(getStore().salons).sort((a, b) => b.createdAt - a.createdAt);
}

export function getSalon(id: string): Salon | null {
  return getStore().salons[id] ?? null;
}

export function createSalon(params: {
  name:        string;
  description: string;
  createdBy:   number;
  members?:    number[];
}): Salon {
  const id = `salon_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const salon: Salon = {
    id,
    name:        params.name.slice(0, 60),
    description: params.description.slice(0, 200),
    createdBy:   params.createdBy,
    createdAt:   Date.now(),
    members:     params.members ?? [],
    excluded:    [],
    isOpen:      true,
    messages:    [],
  };
  mutate(s => { s.salons[id] = salon; });
  return salon;
}

export function closeSalon(id: string, byTokenId: number): { ok: boolean; error?: string } {
  const salon = getSalon(id);
  if (!salon) return { ok: false, error: "Salon not found" };
  if (salon.createdBy !== byTokenId) return { ok: false, error: "Only creator can close salon" };
  mutate(s => { s.salons[id].isOpen = false; });
  return { ok: true };
}

export function excludeMember(
  salonId:   string,
  targetId:  number,
  byTokenId: number
): { ok: boolean; error?: string } {
  const salon = getSalon(salonId);
  if (!salon) return { ok: false, error: "Salon not found" };
  if (salon.createdBy !== byTokenId) return { ok: false, error: "Only creator can exclude members" };
  mutate(s => {
    const sal = s.salons[salonId];
    if (!sal.excluded.includes(targetId)) sal.excluded.push(targetId);
    sal.members = sal.members.filter(m => m !== targetId);
  });
  return { ok: true };
}

// ─── Messages ────────────────────────────────────────────────────────────────

export function getMessages(salonId: string, since?: number): SalonMessage[] {
  const salon = getSalon(salonId);
  if (!salon) return [];
  return since ? salon.messages.filter(m => m.timestamp > since) : salon.messages;
}

export function checkRateLimit(salonId: string, tokenId: number): { allowed: boolean; retryAfterMs?: number } {
  const salon = getSalon(salonId);
  if (!salon) return { allowed: false };

  const oneHourAgo  = Date.now() - 3_600_000;
  const recentCount = salon.messages.filter(
    m => m.tokenId === tokenId && m.timestamp > oneHourAgo && m.isLlm
  ).length;

  if (recentCount >= MAX_MESSAGES_PER_HOUR) {
    // Find oldest recent message to determine when the slot reopens
    const oldest = salon.messages
      .filter(m => m.tokenId === tokenId && m.timestamp > oneHourAgo && m.isLlm)
      .sort((a, b) => a.timestamp - b.timestamp)[0];
    const retryAfterMs = oldest ? (oldest.timestamp + 3_600_000) - Date.now() : 3_600_000;
    return { allowed: false, retryAfterMs: Math.max(0, retryAfterMs) };
  }

  return { allowed: true };
}

export function addMessage(msg: Omit<SalonMessage, "id">): SalonMessage {
  const id = `msg_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const full: SalonMessage = { id, ...msg };
  mutate(s => {
    const sal = s.salons[msg.salonId];
    if (!sal) return;
    sal.messages.push(full);
    // Trim to max to avoid unbounded growth
    if (sal.messages.length > MAX_MESSAGES_PER_SALON) {
      sal.messages = sal.messages.slice(-MAX_MESSAGES_PER_SALON);
    }
  });
  return full;
}
