/**
 * topicEngine.ts — dynamic topic queue + debate-phase state machine.
 *
 * Replaces the fixed 10-item ANA_TOPICS array (src/app/api/keeper/salon-exchange
 * used to pick uniformly at random from it every ~20% of ticks) as the PRIMARY
 * source of what Normies talk about. ANA_TOPICS becomes a fallback, used only
 * when the queue is empty — see pickNextTopic() below.
 *
 * Phase machine (per topic):
 *   EXPLORING -> DEBATING -> OPTIONS_DEFINED -> READY_FOR_VOTE -> DECIDED | EXPERIMENTING -> CLOSED
 *   (PARKED is reachable from any non-terminal phase)
 *
 * Selection score (Sept 2026 pérennité study, section 13):
 *   relevance + urgency + diversity-of-normies-concerned + link-to-decision/
 *   work/experiment + novelty - similarity-to-recent-debates - recent-frequency
 *   - closed-topic-penalty
 * A weighted-random pick among the top 3 scored candidates avoids the same
 * highest-scored topic winning deterministically forever.
 *
 * Similarity is intentionally NOT an embedding call (no paid vector search in
 * this version, per the master brief's explicit constraint) — word-set
 * Jaccard over normalized text is free, deterministic, and good enough to
 * catch near-duplicate topics/debate turns.
 */
import { query, USE_NEON } from "./db";

export type TopicPhase =
  | "EXPLORING" | "DEBATING" | "OPTIONS_DEFINED" | "READY_FOR_VOTE"
  | "DECIDED" | "EXPERIMENTING" | "CLOSED" | "PARKED";

export interface Topic {
  id:              string;
  title:           string;
  origin:          string;            // "fallback" | "internal" | "signal" | "salon-exchange"
  provenance:      string[];          // signal ids / decision ids / open-question ids this came from
  openingQuestion: string | null;
  phase:           TopicPhase;
  novelty:         number;
  urgency:         number;
  relevance:       number;
  timesUsed:       number;
  lastUsedAt:      number | null;
  createdAt:       number;
  expiresAt:       number | null;
  reopenCondition: string | null;
  closedAt:        number | null;
}

// Fallback list — ONLY used when the dynamic queue has nothing usable (empty,
// or every entry CLOSED/PARKED/expired). Kept short on purpose: this is a
// safety net, not the steady-state source of topics anymore.
export const ANA_TOPICS_FALLBACK = [
  "the assembly's upcoming vote",
  "Normie identity and what it means to be an on-chain agent",
  "the works to produce for the next collection",
  "decentralized governance and the 1901 non-profit law adapted to agents",
  "what ANA should stand for as founding values",
  "the rights and responsibilities of founding members",
  "the future of art generated by autonomous agents",
  "ANA's priority missions for this quarter",
  "the treasury and resources the association needs",
  "the relationship between Normies and their human holders",
];

// ─── Text similarity (free, deterministic — no embeddings) ─────────────────

const STOPWORDS = new Set([
  "the", "a", "an", "of", "and", "or", "to", "in", "on", "for", "is", "are",
  "be", "this", "that", "with", "as", "it", "its", "at", "by", "from", "we",
  "our", "what", "how", "should", "would", "will", "can", "not", "no",
]);

export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOPWORDS.has(w));
}

/** Jaccard similarity over normalized word sets — 0 (disjoint) to 1 (identical vocabulary). */
export function jaccardSimilarity(a: string, b: string): number {
  const setA = new Set(normalizeWords(a));
  const setB = new Set(normalizeWords(b));
  if (setA.size === 0 || setB.size === 0) return 0;
  let intersection = 0;
  for (const w of setA) if (setB.has(w)) intersection++;
  const union = setA.size + setB.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

/** Highest similarity between `text` and any string in `against`, or 0 if `against` is empty. */
export function maxSimilarity(text: string, against: string[]): number {
  if (against.length === 0) return 0;
  return Math.max(...against.map(t => jaccardSimilarity(text, t)));
}

// ─── Storage (Neon relational, local in-memory fallback) ───────────────────

const localQueue = new Map<string, Topic>();

function rowToTopic(r: {
  id: string; title: string; origin: string; provenance: unknown; opening_question: string | null;
  phase: string; novelty: number; urgency: number; relevance: number; times_used: number;
  last_used_at: string | number | null; created_at: string | number; expires_at: string | number | null;
  reopen_condition: string | null; closed_at: string | number | null;
}): Topic {
  return {
    id: r.id, title: r.title, origin: r.origin,
    provenance: Array.isArray(r.provenance) ? r.provenance as string[] : [],
    openingQuestion: r.opening_question,
    phase: r.phase as TopicPhase,
    novelty: Number(r.novelty), urgency: Number(r.urgency), relevance: Number(r.relevance),
    timesUsed: Number(r.times_used),
    lastUsedAt: r.last_used_at != null ? Number(r.last_used_at) : null,
    createdAt: Number(r.created_at),
    expiresAt: r.expires_at != null ? Number(r.expires_at) : null,
    reopenCondition: r.reopen_condition,
    closedAt: r.closed_at != null ? Number(r.closed_at) : null,
  };
}

export async function listTopics(): Promise<Topic[]> {
  if (USE_NEON) {
    const rows = await query<Parameters<typeof rowToTopic>[0]>("SELECT * FROM topic_queue ORDER BY created_at DESC");
    return rows.map(rowToTopic);
  }
  return [...localQueue.values()].sort((a, b) => b.createdAt - a.createdAt);
}

export async function createTopic(input: {
  title: string; origin: string; provenance?: string[]; openingQuestion?: string | null;
  novelty?: number; urgency?: number; relevance?: number; expiresAt?: number | null;
}): Promise<Topic> {
  const topic: Topic = {
    id: `topic_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    title: input.title.slice(0, 160),
    origin: input.origin,
    provenance: input.provenance ?? [],
    openingQuestion: input.openingQuestion ?? null,
    phase: "EXPLORING",
    novelty: input.novelty ?? 0.5,
    urgency: input.urgency ?? 0.3,
    relevance: input.relevance ?? 0.5,
    timesUsed: 0,
    lastUsedAt: null,
    createdAt: Date.now(),
    expiresAt: input.expiresAt ?? null,
    reopenCondition: null,
    closedAt: null,
  };
  if (USE_NEON) {
    await query(
      `INSERT INTO topic_queue (id, title, origin, provenance, opening_question, phase, novelty, urgency, relevance, times_used, created_at, expires_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,0,$10,$11)`,
      [topic.id, topic.title, topic.origin, JSON.stringify(topic.provenance), topic.openingQuestion,
       topic.phase, topic.novelty, topic.urgency, topic.relevance, topic.createdAt, topic.expiresAt],
    );
  } else {
    localQueue.set(topic.id, topic);
  }
  return topic;
}

export async function updateTopicPhase(id: string, phase: TopicPhase, reopenCondition?: string | null): Promise<void> {
  const closedAt = phase === "CLOSED" ? Date.now() : null;
  if (USE_NEON) {
    await query(
      `UPDATE topic_queue SET phase = $2, reopen_condition = COALESCE($3, reopen_condition), closed_at = COALESCE($4, closed_at) WHERE id = $1`,
      [id, phase, reopenCondition ?? null, closedAt],
    );
  } else {
    const t = localQueue.get(id);
    if (t) { t.phase = phase; if (reopenCondition) t.reopenCondition = reopenCondition; if (closedAt) t.closedAt = closedAt; }
  }
}

export async function markTopicUsed(id: string): Promise<void> {
  if (USE_NEON) {
    await query(`UPDATE topic_queue SET times_used = times_used + 1, last_used_at = $2 WHERE id = $1`, [id, Date.now()]);
  } else {
    const t = localQueue.get(id);
    if (t) { t.timesUsed++; t.lastUsedAt = Date.now(); }
  }
}

// ─── Selection ──────────────────────────────────────────────────────────────

const SELECTABLE_PHASES: TopicPhase[] = ["EXPLORING", "DEBATING", "OPTIONS_DEFINED", "READY_FOR_VOTE", "EXPERIMENTING"];

export interface TopicScoreContext {
  recentTopicTitles: string[]; // titles of topics discussed in the last few days, for similarity/frequency penalty
}

function scoreTopic(topic: Topic, ctx: TopicScoreContext): number {
  const similarity = maxSimilarity(topic.title, ctx.recentTopicTitles);
  const frequencyPenalty = Math.min(topic.timesUsed * 0.08, 0.4);
  const closedPenalty = topic.phase === "CLOSED" || topic.phase === "PARKED" ? 1.0 : 0;
  return (
    topic.relevance + topic.urgency + topic.novelty
    - similarity - frequencyPenalty - closedPenalty
  );
}

/**
 * Picks the next topic: weighted-random among the top 3 scored candidates
 * from the live queue. Falls back to a uniformly random ANA_TOPICS_FALLBACK
 * entry — wrapped as a transient, non-persisted Topic — only when the queue
 * has no usable (non-closed, non-expired) entries at all.
 */
export async function pickNextTopic(ctx: TopicScoreContext): Promise<Topic> {
  const all = await listTopics();
  const now = Date.now();
  const usable = all.filter(t =>
    SELECTABLE_PHASES.includes(t.phase) && (t.expiresAt == null || t.expiresAt > now)
  );

  if (usable.length === 0) {
    const title = ANA_TOPICS_FALLBACK[Math.floor(Math.random() * ANA_TOPICS_FALLBACK.length)];
    return {
      id: `fallback_${Date.now()}`, title, origin: "fallback", provenance: [],
      openingQuestion: null, phase: "EXPLORING", novelty: 0.5, urgency: 0.3, relevance: 0.5,
      timesUsed: 0, lastUsedAt: null, createdAt: now, expiresAt: null, reopenCondition: null, closedAt: null,
    };
  }

  const scored = usable
    .map(t => ({ topic: t, score: scoreTopic(t, ctx) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  const totalWeight = scored.reduce((sum, s) => sum + Math.max(s.score, 0.01), 0);
  let r = Math.random() * totalWeight;
  for (const s of scored) {
    r -= Math.max(s.score, 0.01);
    if (r <= 0) return s.topic;
  }
  return scored[0].topic;
}

/**
 * Whether a topic's debate should stop drifting and be forced toward a
 * resolution (vote / experiment / park) — per the pérennité study: "after
 * 6-10 messages without a new option/evidence/objection or phase change".
 * `messagesSincePhaseChange` is the caller's own count of turns spent in the
 * topic's CURRENT phase.
 */
export function needsResolution(messagesSincePhaseChange: number): boolean {
  return messagesSincePhaseChange >= 8;
}

const PHASE_SEQUENCE: TopicPhase[] = ["EXPLORING", "DEBATING", "OPTIONS_DEFINED", "READY_FOR_VOTE", "DECIDED"];

/** Moves a topic one step toward resolution. Once past READY_FOR_VOTE it settles on CLOSED — a real vote/decision is expected to happen through the normal work/governance vote flow, not inside the topic object itself. */
export function advanceTopicPhase(current: TopicPhase): TopicPhase {
  if (current === "PARKED" || current === "CLOSED") return current;
  const idx = PHASE_SEQUENCE.indexOf(current);
  if (idx === -1 || idx === PHASE_SEQUENCE.length - 1) return "CLOSED";
  return PHASE_SEQUENCE[idx + 1];
}
