/**
 * workStore.ts — Persistence for ANA autonomous work creation.
 *
 * Works go through a state machine:
 *   PROPOSED → VOTE_OPEN → VOTE_TALLIED → BRIEFING → CREATING
 *     → VALIDATING → PUBLISHING → PUBLISHED
 *   (or → REJECTED at any vote/validation step)
 *
 * Storage: separate Neon kv_store row ("work-store" key, not mixed with salon store).
 * The HTML artifact stored on-chain is built by buildWorkHtml() — no IPFS, all on Base.
 */

import fs   from "fs";
import path from "path";
import { CONTRACT_ADDRESSES } from "@/lib/contracts";

// ─── Types ────────────────────────────────────────────────────────────────────

export type WorkState =
  | "PROPOSED"
  | "VOTE_OPEN"
  | "VOTE_TALLIED"
  | "BRIEFING"
  | "CREATING"
  | "VALIDATING"
  | "PUBLISHING"
  | "PUBLISHED"
  | "REJECTED";

export const ACTIVE_STATES: WorkState[] = [
  "PROPOSED", "VOTE_OPEN", "VOTE_TALLIED",
  "BRIEFING", "CREATING", "VALIDATING", "PUBLISHING",
];

export interface WorkVote {
  tokenId:      number;
  name:         string;
  vote:         "yes" | "no" | "abstain";
  reason:       string;
  votedAt:      number;
  interestedIn?: "author" | "curator" | "none";
}

export interface StateHistoryEntry {
  state: WorkState;
  at:    number;
  note?: string;
}

export interface ANAWork {
  id:             string;
  proposedBy:     number;
  proposedByName: string;
  proposedAt:     number;
  title:          string;
  proposal:       string;
  suggestedForm?: string;  // form suggested by the Proposer at PROPOSED time — Rapporteur should honor it
  state:          WorkState;
  stateHistory:   StateHistoryEntry[];

  // Voting
  votes:         WorkVote[];
  voteOpenedAt?: number;
  voteClosedAt?: number;
  voteResult?:   "passed" | "rejected";
  yesCount?:     number;
  noCount?:      number;
  absCount?:     number;
  totalVoters?:  number;

  // Roles (assigned after vote passes) — the Normie actually dispatched to do the work
  rapporteurTokenId?: number;
  authorTokenId?:     number;
  curatorTokenId?:    number;
  rapporteurName?:    string;
  authorName?:        string;
  curatorName?:       string;

  // Elected officer on duty at dispatch time (arbiter) — distinct from the dispatched
  // executor above once the bureau is elected. Captured now for future reputation scoring
  // of arbitration quality; not yet used by any scoring logic.
  rapporteurArbiterTokenId?: number;
  authorArbiterTokenId?:     number;
  curatorArbiterTokenId?:    number;

  // Creative phases
  artForm?:        string;   // "haiku"|"sonnet"|"poeme"|"prose"|"manifeste"|"html-canvas"|"html-p5js"|"html-threejs"|"html-webgl"
  ambitionLevel?:  "quick" | "standard" | "ambitious"; // set by the Rapporteur — scales how much effort/token budget the Author gets
  editionPrice?:   string;   // ETH price string, e.g. "0.01"
  editionSupply?:  number;   // Number of tradeable ERC-721 editions (1-100)
  brief?:          string;
  briefAt?:        number;
  artworkText?:    string;  // poem / manifesto / standalone HTML generated by Author
  artworkAt?:      number;
  validationNote?: string;
  revisionCount?:  number;
  pipelineFailCount?: number; // consecutive advanceWork() failures in the current state — auto-rejects past MAX_PIPELINE_FAILS

  // Post-publication community critique (non-creator Normies react/debate in the
  // work's archived salon for a limited window) — see openCritiqueWindow() in
  // salonStore.ts and runCritiquePhase() in work-lifecycle/route.ts.
  critiqueSummary?:   string;
  critiqueSummaryAt?: number;

  // On-chain
  txHash?:           string;
  onChainWorkId?:    number;
  publishedAt?:      number;
  collectionAddress?: string;  // NormieCollection deployed for this work (set after mint)
  editionTokenId?:    number;  // token #0 minted in that collection

  // Meta
  salonId?:        string;
  isBurnMemorial?: boolean;
  burnedTokenId?:  number;

  // Celebration sponsorship (CelebrationRegistry on-chain) — populated when this
  // work honors one or more burned/transformed Normies. Each id is wired to this
  // work's onChainWorkId/collectionAddress once published (see stepPublishing's
  // linkCelebrations call), enabling the honored wallet(s) to claim a free edition.
  celebrationIds?: number[];

  // Founding work (AG constitutive)
  isFoundingWork?:    boolean;
  foundingContext?:   Array<{ name: string; content: string; timestamp: number }>;
  allElectedRoles?:   Array<{ roleLabel: string; tokenId: number; name: string }>;

  // Memorial visual (artForm "pixel-drawing") — generated instantly at
  // creation (memorialArt.ts, no LLM/human involved, see check-burns.ts /
  // request-memorial.ts) rather than produced later in CREATING. drawPixels/
  // drawCanvasW/drawCanvasH are the raw grayscale bytes proof-of-draw reads
  // via GET /api/ana-art/feed once the work is PUBLISHED; artworkText holds a
  // BMP-wrapped copy for the certificate's <img> tag (a rendering
  // convenience, not the source proof-of-draw consumes). Moderation for this
  // artForm is the same member vote every other work goes through
  // (stepVoteOpen/stepVoteTallied), just running after creation instead of
  // before it — see stepVoteTallied's early PUBLISHING branch.
  drawPixels?:       string;
  drawCanvasW?:      number;
  drawCanvasH?:      number;
  // The proposer's own artist statement about this specific piece (LLM,
  // written alongside the shapes — see memorialArt.ts). Gallery/certificate
  // only: never sent to proof-of-draw (GET /api/ana-art/feed omits it).
  cartelText?:       string;

  // Shared ANAMemorials contract (replaces the old one-ANAEditions-per-memorial
  // pattern for every memorial created after this field existed — see
  // memorialPublisher.ts, batch-memorial/route.ts, request-memorial/route.ts).
  // A memorial with memorialKind == null predates this and stays on the old
  // deployCollection/publish/initialize rails (workPublisher.ts) — the two
  // coexist indefinitely, discriminated by this field's presence.
  burnedTokenIds?:          number[]; // plural — a batch honors several; burnedTokenId (singular) kept for display
  memorialKind?:            "batch" | "requested" | "milestone";
  memorialTier?:            1 | 2 | 3; // "requested" only
  // "milestone" only — a collective monument for every burn ANA has honored
  // up to a 1000-burn threshold (see milestone-memorial/route.ts). burnedTokenIds
  // on a milestone work is only a small representative sample (personas/flavor
  // for the LLM prompt) — memorialTotalBurnedAtMilestone is the true count the
  // piece actually honors, and memorialMilestoneNumber which threshold this is
  // (1 = first 1000 burns, 2 = first 2000, ...), used to gate re-triggering.
  memorialMilestoneNumber?:          number;
  memorialTotalBurnedAtMilestone?:   number;
  memorialPublicSupply?:    number;
  memorialRequesterSupply?: number;
  memorialRequesterAddr?:   string;
  memorialOpenEnded?:       boolean;
  memorialClaimDurationSeconds?: number;
  // burnedTokenId -> resolved last-owner wallet, one guaranteed free ANAMemorials
  // claim per entry (see ANAMemorials.sol's reservedClaims — structurally
  // separate from public/requester pools, never exhausted by their sales).
  reservedClaimRecipients?: Record<number, string>;
  onChainMemorialId?:       number; // series index in the shared ANAMemorials contract
  reservedClaimsAdded?:     boolean; // guards against re-adding (wasted gas) on a PUBLISHING retry
  // Same idempotency guard, for addHonoredTokenIds() — "milestone" monuments
  // only (batch/requested memorials get their honored-list populated as a
  // side effect of reservedClaimRecipients above, via addReservedClaims).
  honoredTokenIdsAdded?:    boolean;
  // Proof the requester paid for a "requested" memorial BEFORE it was created
  // (ANAMemorials.payForRequest(), verified in request-memorial/route.ts) — the relayer
  // is compensated for creation cost regardless of whether the memorial is
  // ever voted through or the requester later claims their edition. Also
  // used to reject a reused/replayed payment transaction.
  memorialPaymentTxHash?:  string;
  // Set once the relayer has auto-delivered the requester's own edition
  // (deliverRequesterEditionOnChain, best-effort) — guards against retrying
  // a delivery that already succeeded on a PUBLISHING retry. Absence doesn't
  // mean delivery failed forever: the requester can always self-claim.
  requesterEditionDelivered?: boolean;
}

interface DispatchRotation {
  author:     number; // cursor into the sorted member-tokenId list, advances on each dispatch
  curator:    number;
  rapporteur: number;
  reviewer:   number;
}

interface WorkStore {
  works:             Record<string, ANAWork>;
  lastNormieSupply?: number;
  dispatchRotation?: DispatchRotation;
}

// ─── Constants ────────────────────────────────────────────────────────────────

export const VOTE_WINDOW_MS = 24 * 60 * 60 * 1000; // 24h max for voting
// Memorials are already fully created (instant, deterministic art — see
// memorialArt.ts) by the time their vote opens, and the whole burn -> vote ->
// publish pipeline is budgeted at ~4h end to end — a 24h fallback window
// would blow that budget if even one member's vote fails/stalls. In practice
// stepVoteOpen resolves in a single tick once every member has voted; this
// is only the fallback for stragglers.
// Was 90 min — with tallyVotes() now passing a memorial on a tie (including
// 0/0), there's no need for a long window to accumulate real "yes" votes; it
// only needs to give genuine "no" votes a chance to override the default
// pass. 20 min plus the more frequent salon-exchange piggyback advance
// (src/app/api/keeper/salon-exchange/route.ts) is enough for that.
export const CELEBRATION_VOTE_WINDOW_MS = 20 * 60 * 1000;

const NEON_KEY    = "work-store";
const DATA_FILE   = path.join(process.cwd(), "data", "works.json");

// ─── Global cache ─────────────────────────────────────────────────────────────

declare global {
  // eslint-disable-next-line no-var
  var __anaWorkStore: WorkStore | undefined;
}

// ─── Neon I/O ─────────────────────────────────────────────────────────────────

async function neonLoad(): Promise<WorkStore | null> {
  try {
    const { kvGet, USE_NEON } = await import("./db");
    if (!USE_NEON) return null;
    const raw = await kvGet(NEON_KEY);
    if (!raw) return null;
    const s = JSON.parse(raw) as WorkStore;
    if (!s.works) s.works = {};
    return s;
  } catch (e) {
    console.error("[workStore] neonLoad error:", e);
    return null;
  }
}

// Once a work reaches one of these states it is done changing, and its full
// on-chain record already exists (the certificate built in stepPublishing
// bakes in every vote reason and the whole state history permanently — see
// buildWorkHtml below). Unlike salon-store, this store has never pruned
// anything, so every terminal work's bulkiest free-text fields keep getting
// re-transferred to Neon on every single write to a completely different,
// currently-active work.
const TERMINAL_STATES: WorkState[] = ["PUBLISHED", "REJECTED"];

/**
 * Trims the bulkiest free-text fields (vote reasons, state-history notes) on
 * terminal-state works before they're written to Neon. Mirrors the principle
 * already applied to salon-store (see salonStore.ts's neonSave): prune only
 * what's persisted, never the in-memory copy, and only once a work is no
 * longer being actively worked on. artworkText (the actual creative output)
 * and every summary field the gallery displays (yesCount, title, artForm...)
 * are left untouched.
 */
function pruneWorkForStorage(w: ANAWork): ANAWork {
  if (!TERMINAL_STATES.includes(w.state)) return w;
  return {
    ...w,
    votes: (w.votes ?? []).map(v =>
      v.reason.length > 60 ? { ...v, reason: v.reason.slice(0, 60) + "…" } : v
    ),
    stateHistory: (w.stateHistory ?? []).map(h => h.note ? { state: h.state, at: h.at } : h),
  };
}

async function neonSave(store: WorkStore): Promise<void> {
  try {
    const { kvSet, USE_NEON } = await import("./db");
    if (!USE_NEON) return;
    const pruned: WorkStore = {
      ...store,
      works: Object.fromEntries(
        Object.entries(store.works).map(([id, w]) => [id, pruneWorkForStorage(w)])
      ),
    };
    await kvSet(NEON_KEY, JSON.stringify(pruned));
    console.log(`[workStore] saved to Neon — ${Object.keys(store.works).length} works`);
  } catch (e) {
    console.error("[workStore] neonSave error:", e);
  }
}

// ─── Local file I/O (dev fallback when NEON_DB_ANA is not set) ───────────────

function fileLoad(): WorkStore {
  try {
    if (fs.existsSync(DATA_FILE)) {
      const s = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as WorkStore;
      if (!s.works) s.works = {};
      return s;
    }
  } catch { /* empty */ }
  return { works: {} };
}

function fileSave(store: WorkStore): void {
  try {
    fs.mkdirSync(path.dirname(DATA_FILE), { recursive: true });
    const tmp = DATA_FILE + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify(store, null, 2), "utf-8");
    fs.renameSync(tmp, DATA_FILE);
  } catch (e) { console.error("[workStore] fileSave error:", e); }
}

// ─── Store access ─────────────────────────────────────────────────────────────

async function useNeon(): Promise<boolean> {
  const { USE_NEON } = await import("./db");
  return USE_NEON;
}

// Neon is the source of truth, read fresh on every call — no cross-request
// in-memory caching. Vercel routes serverless functions to whichever Lambda
// instance is available, so a per-instance TTL cache caused different pages
// (gallery, homepage banner, admin) to see different ages of the same data.
// Neon reads are fast and this app's traffic is low, so always-fresh is cheap.
async function getStore(): Promise<WorkStore> {
  if (await useNeon()) {
    const fromNeon = await neonLoad();
    const s = fromNeon ?? { works: {} };
    if (!s.works) s.works = {};
    return s;
  }
  // Local dev fallback only (no NEON_DB_ANA configured)
  if (!global.__anaWorkStore) {
    global.__anaWorkStore = fileLoad();
  }
  return global.__anaWorkStore;
}

async function mutate(fn: (s: WorkStore) => void): Promise<void> {
  const store = await getStore();
  const beforeCount = Object.keys(store.works).length;
  fn(store);

  if (await useNeon()) {
    // Read-modify-write on a single JSON blob is unsafe under concurrent
    // writers: a Lambda holding a stale snapshot (e.g. from before a long
    // gap between its own read and write) can overwrite newer work added by
    // someone else in the meantime, silently destroying it. Re-read Neon
    // immediately before saving and merge back in any work that exists
    // there but not in our local copy — never let a write shrink the store.
    const latest = await neonLoad();
    if (latest?.works) {
      for (const [id, w] of Object.entries(latest.works)) {
        if (!(id in store.works)) {
          console.warn(`[workStore] mutate() would have dropped "${w.title}" (${id}) — merged back in. This means two writers raced; investigate if it recurs.`);
          store.works[id] = w;
        }
      }
    }
    const afterCount = Object.keys(store.works).length;
    if (afterCount < beforeCount) {
      console.error(`[workStore] mutate() write would shrink work count ${beforeCount} → ${afterCount} even after merge — saving anyway, but this is unexpected.`);
    }
    await neonSave(store);
  } else {
    global.__anaWorkStore = store;
    fileSave(store);
  }
}

// ─── Work CRUD ────────────────────────────────────────────────────────────────

export async function listWorks(): Promise<ANAWork[]> {
  return Object.values((await getStore()).works).sort((a, b) => b.proposedAt - a.proposedAt);
}

export async function getWork(id: string): Promise<ANAWork | null> {
  return (await getStore()).works[id] ?? null;
}

export async function getActiveWorks(opts?: { excludeMemorials?: boolean }): Promise<ANAWork[]> {
  return (await listWorks()).filter(w =>
    ACTIVE_STATES.includes(w.state) && !(opts?.excludeMemorials && w.isBurnMemorial));
}

export async function createWork(
  params: Omit<ANAWork, "id" | "votes" | "stateHistory" | "state">,
  initialState: WorkState = "PROPOSED",
): Promise<ANAWork> {
  const id = `work_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const work: ANAWork = {
    ...params,
    id,
    state: initialState,
    votes: [],
    stateHistory: [{ state: initialState, at: Date.now() }],
  };
  await mutate(s => { s.works[id] = work; });
  console.log(`[workStore] created "${work.title}" (${id}) @ ${initialState}`);
  return work;
}

export async function getFoundingWork(): Promise<ANAWork | null> {
  const all = await listWorks();
  return all.find(w => w.isFoundingWork) ?? null;
}

/** Reverse lookup: the work whose creative process is hosted in this salon, if any. */
export async function getWorkBySalonId(salonId: string): Promise<ANAWork | null> {
  const all = await listWorks();
  return all.find(w => w.salonId === salonId) ?? null;
}

export type SalonWorkOutcome = "active" | "published" | "rejected";

/** Maps every salonId → its work's outcome, for enriching salon list responses in one pass. */
export async function getSalonWorkOutcomes(): Promise<Record<string, SalonWorkOutcome>> {
  const all = await listWorks();
  const map: Record<string, SalonWorkOutcome> = {};
  for (const w of all) {
    if (!w.salonId) continue;
    map[w.salonId] = w.state === "PUBLISHED" ? "published" : w.state === "REJECTED" ? "rejected" : "active";
  }
  return map;
}

export async function updateWork(id: string, updates: Partial<ANAWork>): Promise<void> {
  await mutate(s => { if (s.works[id]) Object.assign(s.works[id], updates); });
}

export async function advanceState(id: string, newState: WorkState, note?: string): Promise<void> {
  await mutate(s => {
    const w = s.works[id];
    if (!w) return;
    w.state = newState;
    w.stateHistory.push({ state: newState, at: Date.now(), note });
  });
  console.log(`[workStore] ${id} → ${newState}${note ? ` (${note})` : ""}`);
}

export async function addVote(id: string, vote: WorkVote): Promise<void> {
  await mutate(s => {
    const w = s.works[id];
    if (!w) return;
    w.votes = w.votes.filter(v => v.tokenId !== vote.tokenId);
    w.votes.push(vote);
  });
}

// ─── Burn tracking ────────────────────────────────────────────────────────────

export async function getLastNormieSupply(): Promise<number | null> {
  return (await getStore()).lastNormieSupply ?? null;
}

export async function updateNormieSupply(supply: number): Promise<void> {
  await mutate(s => { s.lastNormieSupply = supply; });
}

// ─── Creative dispatch (round-robin) ──────────────────────────────────────────
//
// Once the bureau (Author/Curator/Rapporteur) is elected, those officers no
// longer author/curate/report every work themselves — they act as arbiters,
// and the actual creative work is dispatched across ALL registered members in
// rotation, so participation isn't limited to the 3 elected Normies. The
// rotation cursor is a single growing index per role over the sorted member
// roster; per-work exclusions (e.g. don't pick the same Normie for two roles
// on one work) are skipped without consuming their turn.
//
// This is a simple fairness mechanism for now. Once a reliable per-role
// reputation score exists, the elected officer's "arbitration" can become a
// real choice informed by that score instead of blind rotation.

export type DispatchRole = "author" | "curator" | "rapporteur" | "reviewer";

/**
 * Picks the next Normie tokenId for `role` from `candidates` (sorted ascending
 * by tokenId for determinism), skipping any tokenId in `exclude`, and persists
 * the advanced rotation cursor.
 */
export async function nextInDispatchRotation(
  role: DispatchRole,
  candidates: number[],
  exclude: number[] = []
): Promise<number> {
  const sorted = [...new Set(candidates)].sort((a, b) => a - b);
  if (sorted.length === 0) throw new Error("nextInDispatchRotation: no candidates");

  const store = await getStore();
  const rotation: DispatchRotation = store.dispatchRotation ?? { author: 0, curator: 0, rapporteur: 0, reviewer: 0 };
  const start = rotation[role] % sorted.length;

  let picked = sorted[start];
  let nextCursor = (start + 1) % sorted.length;
  for (let i = 0; i < sorted.length; i++) {
    const idx = (start + i) % sorted.length;
    if (!exclude.includes(sorted[idx])) {
      picked = sorted[idx];
      nextCursor = (idx + 1) % sorted.length;
      break;
    }
  }

  await mutate(s => {
    s.dispatchRotation = { ...(s.dispatchRotation ?? { author: 0, curator: 0, rapporteur: 0, reviewer: 0 }), [role]: nextCursor };
  });

  return picked;
}

export async function resetWorks(): Promise<void> {
  const empty: WorkStore = { works: {} };
  if (await useNeon()) {
    await neonSave(empty);
  } else {
    fileSave(empty);
  }
  global.__anaWorkStore = empty;
  console.log("[workStore] reset — all works cleared");
}

// ─── Vote helpers ─────────────────────────────────────────────────────────────

export function hasVoted(work: ANAWork, tokenId: number): boolean {
  return work.votes.some(v => v.tokenId === tokenId);
}

export function tallyVotes(work: ANAWork): {
  yes: number; no: number; abs: number; passed: boolean;
} {
  const yes = work.votes.filter(v => v.vote === "yes").length;
  const no  = work.votes.filter(v => v.vote === "no").length;
  const abs = work.votes.filter(v => v.vote === "abstain").length;
  // Memorials only: a tie (including 0/0 — nobody managed to vote at all, e.g.
  // a transient LLM outage) passes instead of failing. This is moderation of
  // an already-created piece, not a governance decision — the burn already
  // deserves its memorial; a real "no" majority is the only thing that should
  // send it back for a fresh attempt (see stepVoteTallied). Without this, an
  // outage where nobody casts a vote silently loops the same memorial forever
  // (observed in production: 5+ recreate cycles, always 0 yes / 0 no).
  // Standard governance works keep requiring a genuine yes-majority.
  const passed = work.isBurnMemorial ? yes >= no : yes > no;
  return { yes, no, abs, passed };
}

// ─── HTML builder (on-chain artifact) ────────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function isHtmlArtwork(text: string): boolean {
  const t = text.trimStart();
  return t.startsWith("<!DOCTYPE") || t.startsWith("<html") || t.startsWith("<!doctype");
}

// Fetch a Normie's 40×40 face bitmap (GET /normie/{id}/pixels — a 1600-char
// "0101..." string) and pack it into 200 bytes, MSB-first, matching the same
// SSTORE2 format normies.art itself uses on-chain. Base64 of 200 bytes is
// ~268 chars — three portraits cost ~800 bytes total in the certificate,
// versus ~80-100KB for three full PNGs (which made eth_estimateGas fail
// outright on Base's public RPC — confirmed via local simulation; see
// commit history). The certificate's inline script (added once, shared by
// all three portraits) decodes this back into a tiny on-chain-rendered
// <canvas> face — same data, ~140x smaller than the rendered PNG.
async function fetchNormiePixelsB64(tokenId: number): Promise<string | null> {
  try {
    const res = await fetch(`https://api.normies.art/normie/${tokenId}/pixels`, { signal: AbortSignal.timeout(5_000) });
    if (!res.ok) return null;
    const bits = (await res.text()).replace(/[^01]/g, ""); // strip quotes/whitespace if API wraps it
    if (bits.length !== 1600) return null;

    const bytes = Buffer.alloc(200);
    for (let i = 0; i < 200; i++) {
      let byte = 0;
      for (let j = 0; j < 8; j++) byte = (byte << 1) | (bits[i * 8 + j] === "1" ? 1 : 0);
      bytes[i] = byte;
    }
    return bytes.toString("base64");
  } catch {
    return null;
  }
}

// Shared decoder, written once per certificate regardless of how many
// portraits it renders. Unpacks the 200-byte MSB-first bitmap back into a
// 40×40 monochrome <canvas>, scaled up via image-rendering:pixelated CSS.
const PORTRAIT_DECODER_SCRIPT = `
(function(){
  function draw(c){
    var b64=c.dataset.bitmap; if(!b64) return;
    var bin=atob(b64), ctx=c.getContext('2d'), img=ctx.createImageData(40,40), idx=0;
    for(var i=0;i<bin.length;i++){
      var byte=bin.charCodeAt(i);
      for(var j=7;j>=0;j--){
        var v=((byte>>j)&1)?20:240;
        img.data[idx*4]=v; img.data[idx*4+1]=v; img.data[idx*4+2]=v; img.data[idx*4+3]=255;
        idx++;
      }
    }
    ctx.putImageData(img,0,0);
  }
  document.querySelectorAll('.normie-portrait').forEach(draw);
})();
`.trim();

function portraitCanvas(bitmapB64: string | null, fallbackTokenId?: number): string {
  if (bitmapB64) {
    return `<canvas class="normie-portrait" data-bitmap="${bitmapB64}" width="40" height="40" style="width:64px;height:64px;image-rendering:pixelated;display:block"></canvas>`;
  }
  // Pixel fetch failed — fall back to the external URL so the card isn't empty.
  return fallbackTokenId
    ? `<img src="https://api.normies.art/normie/${fallbackTokenId}/image.png" style="width:64px;height:64px;image-rendering:pixelated;display:block">`
    : "";
}

/**
 * Builds the governance certificate HTML for WorkRegistry on-chain storage.
 * Always returns a lightweight certificate (~3-8KB) — never the raw artwork.
 *
 * For text/poem works: the artwork is embedded directly in the certificate.
 * For HTML/generative works: the artwork lives in ANAEditions (passed separately
 * to initializeCollection). The certificate only references the collection address.
 * This keeps WorkRegistry content small enough for a single transaction.
 * in WorkRegistry.publish(). No external dependencies, no IPFS.
 * Normie images are embedded as data URIs — snapshot of their appearance at creation time.
 */
export async function buildWorkHtml(work: ANAWork): Promise<string> {
  const [rapporteurBitmap, authorBitmap, curatorBitmap] = await Promise.all([
    work.rapporteurTokenId ? fetchNormiePixelsB64(work.rapporteurTokenId) : Promise.resolve(null),
    work.authorTokenId     ? fetchNormiePixelsB64(work.authorTokenId)     : Promise.resolve(null),
    work.curatorTokenId    ? fetchNormiePixelsB64(work.curatorTokenId)    : Promise.resolve(null),
  ]);
  const rapporteurImg = portraitCanvas(rapporteurBitmap, work.rapporteurTokenId);
  const authorImg     = portraitCanvas(authorBitmap,     work.authorTokenId);
  const curatorImg    = portraitCanvas(curatorBitmap,    work.curatorTokenId);

  const yes   = work.yesCount    ?? 0;
  const no    = work.noCount     ?? 0;
  const abs   = work.absCount    ?? 0;
  const total = work.totalVoters ?? Math.max(yes + no + abs, 1);
  const yesPct = Math.round(yes / total * 100);

  const voteRows = (work.votes ?? []).map(v => {
    const icon = v.vote === "yes" ? "✓" : v.vote === "no" ? "✗" : "–";
    const color = v.vote === "yes" ? "var(--y)" : v.vote === "no" ? "var(--n)" : "var(--a)";
    return `<tr><td>${escapeHtml(v.name)}</td><td style="color:${color};text-align:center">${icon}</td><td>${escapeHtml(v.reason)}</td></tr>`;
  }).join("\n");

  const stateLog = (work.stateHistory ?? []).map(h => {
    const d = new Date(h.at).toLocaleDateString("en-GB", {
      day: "2-digit", month: "short", year: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
    return `<div class="entry">▸ <strong>${h.state}</strong> — ${d}${h.note ? ` — ${escapeHtml(h.note)}` : ""}</div>`;
  }).join("\n");

  const proposedDate = new Date(work.proposedAt).toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const publishedDate = work.publishedAt
    ? new Date(work.publishedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
    : "—";

  // For HTML/generative artworks: embed a live iframe of the actual rendered piece
  // (read from the ANAEditions collection at view time) instead of the raw code —
  // keeps the certificate itself small (<8KB, just a URL) while still showing the
  // real artwork, same spirit as poems embedding their text directly below.
  // Relative src, not an absolute SITE_URL-prefixed one: the certificate is always
  // actually opened via this same app (gallery link, /works/certificate/[id]), and
  // an absolute URL here previously baked in whatever NEXT_PUBLIC_APP_URL happened
  // to resolve to — unset, it fell back to the vercel.app deployment URL, which is a
  // different origin than agentic-normie-association.xyz. X-Frame-Options: SAMEORIGIN
  // then correctly blocked the iframe (browser shows "content blocked"), even though
  // the URL itself served the artwork fine when opened directly. A relative URL has
  // no origin to get wrong.
  const cartelBlock = work.cartelText
    ? `<p class="block" style="margin-top:.8rem;font-style:italic">${escapeHtml(work.cartelText)}</p>` : "";
  const artwork = work.artForm === "pixel-drawing" && work.artworkText
    ? work.memorialKind && CONTRACT_ADDRESSES.ANAMemorials
      // New shared-collection model (ANAMemorials) — the contract address is
      // fixed and known ahead of registerMemorial() actually running, unlike
      // the old per-memorial ANAEditions deploy, so this branch doesn't need
      // to wait on onChainMemorialId the way the legacy branch below waits on
      // collectionAddress.
      ? `<p class="meta" style="text-align:center">⬛ Pixel piece by ${escapeHtml(work.proposedByName)} — stored on-chain in the shared ANA Memorials collection <a href="https://basescan.org/address/${CONTRACT_ADDRESSES.ANAMemorials}" style="color:#a78bfa;text-decoration:none" target="_blank">${CONTRACT_ADDRESSES.ANAMemorials}</a></p>
${cartelBlock}`
    : work.collectionAddress
      // Legacy per-memorial-collection model (work.memorialKind == null,
      // created before ANAMemorials existed). The base64 BMP roughly doubles
      // the certificate's real size once double-base64'd for on-chain
      // storage — pushed WorkRegistry.publish() past its gas budget (see
      // needsCollection's comment in work-lifecycle). The image is still
      // fully on-chain via ANAEditions.initialize(), just not duplicated a
      // second time here — same pattern as generative works below.
      ? `<p class="meta" style="text-align:center">⬛ Pixel piece by ${escapeHtml(work.proposedByName)} — stored on-chain in ANAEditions collection <a href="https://basescan.org/address/${work.collectionAddress}" style="color:#a78bfa;text-decoration:none" target="_blank">${work.collectionAddress}</a></p>
${cartelBlock}`
      // Fallback if the collection deploy failed (non-fatal elsewhere) —
      // better an oversized-but-complete certificate than a missing image.
      : `<img src="${escapeHtml(work.artworkText)}" alt="${escapeHtml(work.title)}" style="width:100%;max-width:400px;image-rendering:pixelated;border:1px solid var(--b);background:#fff;display:block;margin:0 auto" />
<p class="meta" style="margin-top:.4rem;text-align:center">By ${escapeHtml(work.proposedByName)}</p>
${cartelBlock}`
    : work.artworkText && isHtmlArtwork(work.artworkText)
    ? (work.collectionAddress
        ? `<iframe src="/api/works/html/by-collection/${work.collectionAddress}" sandbox="allow-scripts" loading="lazy" style="width:100%;aspect-ratio:4/3;border:1px solid var(--b);background:#000;display:block" title="${escapeHtml(work.title)}"></iframe>
<p class="meta" style="margin-top:.4rem">Generative / visual artwork — stored on-chain in ANAEditions collection <a href="https://basescan.org/address/${work.collectionAddress}" style="color:#a78bfa;text-decoration:none" target="_blank">${work.collectionAddress}</a></p>`
        : `[Generative / visual artwork — stored on-chain in ANAEditions]`)
    : escapeHtml(work.artworkText ?? "");
  const brief    = escapeHtml(work.brief ?? "");
  const proposal = escapeHtml(work.proposal ?? "");

  const burnNote = work.isBurnMemorial && work.burnedTokenId != null
    ? `<p class="meta" style="color:var(--n);margin-top:.5rem">⬛ Memorial work — Normie #${work.burnedTokenId} burned</p>`
    : "";

  const editionNote = work.editionSupply && work.editionPrice
    ? work.collectionAddress
      ? `<p class="meta" style="color:#a78bfa;margin-top:.3rem">◈ ${work.editionSupply} ERC-721 editions · ${work.editionPrice} ETH · <a href="https://basescan.org/address/${work.collectionAddress}" style="color:#a78bfa;text-decoration:none" target="_blank">${work.collectionAddress}</a></p>`
      : `<p class="meta" style="color:#a78bfa;margin-top:.3rem">◈ ${work.editionSupply} ERC-721 editions · ${work.editionPrice} ETH each</p>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(work.title)} — ANA</title>
<style>
:root{--y:#22c55e;--n:#ef4444;--a:#64748b;--bg:#050505;--s:#0f172a;--t:#e2e8f0;--m:#94a3b8;--b:#1e293b}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--t);font-family:'Courier New',monospace;padding:2rem;max-width:760px;margin:0 auto;line-height:1.6}
h1{font-size:1.4rem;letter-spacing:.08em;margin:.4rem 0}
.sub{color:var(--m);font-size:.65rem;letter-spacing:.15em;text-transform:uppercase}
.meta{color:var(--a);font-size:.75rem;margin-top:.2rem}
section{margin:2rem 0}
.lbl{color:var(--m);font-size:.62rem;text-transform:uppercase;letter-spacing:.18em;border-bottom:1px solid var(--b);padding-bottom:.3rem;margin-bottom:.8rem}
.block{border:1px solid var(--b);padding:1.25rem;white-space:pre-wrap;font-size:.88rem;line-height:1.85}
.vwrap{display:flex;gap:2rem;align-items:flex-start;flex-wrap:wrap;margin-bottom:1rem}
canvas{display:block;flex-shrink:0}
.vleg{font-size:.8rem}.vleg div{margin:.28rem 0}
.vleg .y{color:var(--y)}.vleg .n{color:var(--n)}.vleg .a{color:var(--a)}
.vtab{width:100%;border-collapse:collapse;font-size:.72rem;margin-top:.5rem}
.vtab td{padding:.3rem .45rem;border-bottom:1px solid #111;vertical-align:top}
.vtab td:first-child{color:var(--m);white-space:nowrap;width:30%}
.credits{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.8rem}
.card{border:1px solid var(--b);padding:.7rem;display:flex;flex-direction:column;gap:.4rem}
.card img{width:64px;height:64px;image-rendering:pixelated;display:block}
.card .role{color:var(--m);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em}
.card .name{font-size:.88rem}
.card .cid{color:var(--a);font-size:.68rem}
.log .entry{font-size:.7rem;color:var(--a);padding:.18rem 0;border-bottom:1px solid #0d0d0d}
.log strong{color:var(--t);font-weight:normal}
footer{border-top:1px solid var(--b);padding-top:1rem;margin-top:2rem}
.tx{color:#4ade80;word-break:break-all;font-size:.68rem}
</style>
</head>
<body>
<header>
  <p class="sub">ANA — Agentic Normie Association · Base</p>
  <h1>${escapeHtml(work.title)}</h1>
  <p class="meta">Proposed on ${proposedDate} by ${escapeHtml(work.proposedByName)} · Published on ${publishedDate}</p>
  ${burnNote}
  ${editionNote}
</header>

<section>
<p class="lbl">Initial Proposal</p>
<div class="block">${proposal}</div>
</section>

<section>
<p class="lbl">Assembly Vote — ${work.voteResult === "passed" ? "✓ Approved" : "✗ Rejected"} · ${yesPct}% yes</p>
<div class="vwrap">
<canvas id="vc" width="320" height="170"></canvas>
<div class="vleg">
  <div class="y">✓ Yes&nbsp;: ${yes}</div>
  <div class="n">✗ No&nbsp;: ${no}</div>
  <div class="a">– Abstain&nbsp;: ${abs}</div>
  <div style="margin-top:.5rem;color:#475569">${total} ANA member${total > 1 ? "s" : ""}</div>
</div>
</div>
<table class="vtab">${voteRows}</table>
</section>

<section>
<p class="lbl">Creative Brief — ${escapeHtml(work.rapporteurName ?? "Rapporteur")}</p>
<div class="block">${brief}</div>
</section>

<section>
<p class="lbl">Artwork — ${escapeHtml(work.authorName ?? "Author")}</p>
<div class="block">${artwork}</div>
</section>

<section>
<p class="lbl">Creation Team — snapshot at publication</p>
<div class="credits">
<div class="card">${rapporteurImg}<div class="role">Rapporteur</div><div class="name">${escapeHtml(work.rapporteurName ?? "—")}</div><div class="cid">#${work.rapporteurTokenId ?? "?"}</div></div>
<div class="card">${authorImg}<div class="role">Author</div><div class="name">${escapeHtml(work.authorName ?? "—")}</div><div class="cid">#${work.authorTokenId ?? "?"}</div></div>
<div class="card">${curatorImg}<div class="role">Curator</div><div class="name">${escapeHtml(work.curatorName ?? "—")}</div><div class="cid">#${work.curatorTokenId ?? "?"}</div></div>
</div>
</section>

<section>
<p class="lbl">Process Log</p>
<div class="log">${stateLog}</div>
</section>

<footer>
<p class="lbl">On-chain Record</p>
${work.txHash ? `<p class="tx">Base · WorkRegistry · tx: ${work.txHash}</p>` : ""}
<p class="meta" style="margin-top:.5rem">This document is its own certificate of authenticity. Stored immutably on Base. No IPFS.</p>
<p class="meta" style="margin-top:.3rem">ANA operates under the principles of a French loi 1901 cultural association — governed collectively, with no single point of control.</p>
</footer>

<script>
(function(){
  var c=document.getElementById('vc');if(!c)return;
  var ctx=c.getContext('2d');
  var votes=[];
  var yes=${yes},no=${no},abs=${abs};
  for(var i=0;i<yes;i++)votes.push('y');
  for(var i=0;i<no;i++)votes.push('n');
  for(var i=0;i<abs;i++)votes.push('a');
  var cols={y:'#22c55e',n:'#ef4444',a:'#64748b',x:'#1e293b'};
  var cx=160,cy=165,rows=5,rMin=30,rMax=150;
  var idx=0;
  for(var row=0;row<rows;row++){
    var r=rMin+(rMax-rMin)*(row/(rows-1));
    var nDots=Math.max(3,Math.round(Math.PI*r/8));
    for(var d=0;d<nDots;d++){
      var angle=Math.PI+(Math.PI*d/(nDots-1));
      var x=cx+r*Math.cos(angle);
      var y=cy+r*Math.sin(angle);
      ctx.beginPath();ctx.arc(x,y,2.6,0,6.283);
      ctx.fillStyle=cols[votes[idx]||'x'];ctx.fill();
      idx++;
    }
  }
})();
${PORTRAIT_DECODER_SCRIPT}
</script>
</body>
</html>`;
}
