/**
 * workStore.ts — Persistence for ANA autonomous work creation.
 *
 * Works go through a state machine:
 *   PROPOSED → VOTE_OPEN → VOTE_TALLIED → BRIEFING → CREATING
 *     → VALIDATING → PUBLISHING → PUBLISHED
 *   (or → REJECTED at any vote/validation step)
 *
 * Storage: separate Vercel Blob at work/store.json (not mixed with salon store).
 * The HTML artifact stored on-chain is built by buildWorkHtml() — no IPFS, all on Base.
 */

import fs   from "fs";
import path from "path";

// ─── Types ────────────────────────────────────────────────────────────────────

export type WorkState =
  | "PROPOSED"
  | "VOTE_OPEN"
  | "VOTE_TALLIED"
  | "BRIEFING"
  | "CREATING"
  | "VALIDATING"
  | "PUBLISHING"
  | "PUBLISHED"
  | "REJECTED";

export const ACTIVE_STATES: WorkState[] = [
  "PROPOSED", "VOTE_OPEN", "VOTE_TALLIED",
  "BRIEFING", "CREATING", "VALIDATING", "PUBLISHING",
];

export interface WorkVote {
  tokenId:      number;
  name:         string;
  vote:         "yes" | "no" | "abstain";
  reason:       string;
  votedAt:      number;
  interestedIn?: "author" | "curator" | "none";
}

export interface StateHistoryEntry {
  state: WorkState;
  at:    number;
  note?: string;
}

export interface ANAWork {
  id:             string;
  proposedBy:     number;
  proposedByName: string;
  proposedAt:     number;
  title:          string;
  proposal:       string;
  state:          WorkState;
  stateHistory:   StateHistoryEntry[];

  // Voting
  votes:         WorkVote[];
  voteOpenedAt?: number;
  voteClosedAt?: number;
  voteResult?:   "passed" | "rejected";
  yesCount?:     number;
  noCount?:      number;
  absCount?:     number;
  totalVoters?:  number;

  // Roles (assigned after vote passes)
  rapporteurTokenId?: number;
  authorTokenId?:     number;
  curatorTokenId?:    number;
  rapporteurName?:    string;
  authorName?:        string;
  curatorName?:       string;

  // Creative phases
  artForm?:        string;   // "haiku"|"sonnet"|"poeme"|"prose"|"manifeste"|"html-canvas"|"html-p5js"|"html-threejs"|"html-webgl"
  editionPrice?:   string;   // ETH price string, e.g. "0.01"
  editionSupply?:  number;   // Number of tradeable ERC-721 editions (1-100)
  brief?:          string;
  briefAt?:        number;
  artworkText?:    string;  // poem / manifesto / standalone HTML generated by Author
  artworkAt?:      number;
  validationNote?: string;
  revisionCount?:  number;
  pipelineFailCount?: number; // consecutive advanceWork() failures in the current state — auto-rejects past MAX_PIPELINE_FAILS

  // On-chain
  txHash?:           string;
  onChainWorkId?:    number;
  publishedAt?:      number;
  collectionAddress?: string;  // NormieCollection deployed for this work (set after mint)
  editionTokenId?:    number;  // token #0 minted in that collection

  // Meta
  salonId?:        string;
  isBurnMemorial?: boolean;
  burnedTokenId?:  number;

  // Founding work (AG constitutive)
  isFoundingWork?:    boolean;
  foundingContext?:   Array<{ name: string; content: string; timestamp: number }>;
  allElectedRoles?:   Array<{ roleLabel: string; tokenId: number; name: string }>;
}

interface WorkStore {
  works:             Record<string, ANAWork>;
  lastNormieSupply?: number;
}

// ─── Constants ────────────────────────────────────────────────────────────────

export const VOTE_WINDOW_MS = 24 * 60 * 60 * 1000; // 24h max for voting

const NEON_KEY    = "work-store";
const DATA_FILE   = path.join(process.cwd(), "data", "works.json");

// ─── Global cache ─────────────────────────────────────────────────────────────

declare global {
  // eslint-disable-next-line no-var
  var __anaWorkStore: WorkStore | undefined;
}

// ─── Neon I/O ─────────────────────────────────────────────────────────────────

async function neonLoad(): Promise<WorkStore | null> {
  try {
    const { kvGet, USE_NEON } = await import("./db");
    if (!USE_NEON) return null;
    const raw = await kvGet(NEON_KEY);
    if (!raw) return null;
    const s = JSON.parse(raw) as WorkStore;
    if (!s.works) s.works = {};
    return s;
  } catch (e) {
    console.error("[workStore] neonLoad error:", e);
    return null;
  }
}

async function neonSave(store: WorkStore): Promise<void> {
  try {
    const { kvSet, USE_NEON } = await import("./db");
    if (!USE_NEON) return;
    await kvSet(NEON_KEY, JSON.stringify(store));
    console.log(`[workStore] saved to Neon — ${Object.keys(store.works).length} works`);
  } catch (e) {
    console.error("[workStore] neonSave error:", e);
  }
}

// ─── Local file I/O (dev fallback when NEON_DB_ANA is not set) ───────────────

function fileLoad(): WorkStore {
  try {
    if (fs.existsSync(DATA_FILE)) {
      const s = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as WorkStore;
      if (!s.works) s.works = {};
      return s;
    }
  } catch { /* empty */ }
  return { works: {} };
}

function fileSave(store: WorkStore): void {
  try {
    fs.mkdirSync(path.dirname(DATA_FILE), { recursive: true });
    const tmp = DATA_FILE + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify(store, null, 2), "utf-8");
    fs.renameSync(tmp, DATA_FILE);
  } catch (e) { console.error("[workStore] fileSave error:", e); }
}

// ─── Store access ─────────────────────────────────────────────────────────────

async function useNeon(): Promise<boolean> {
  const { USE_NEON } = await import("./db");
  return USE_NEON;
}

// Neon is the source of truth, read fresh on every call — no cross-request
// in-memory caching. Vercel routes serverless functions to whichever Lambda
// instance is available, so a per-instance TTL cache caused different pages
// (gallery, homepage banner, admin) to see different ages of the same data.
// Neon reads are fast and this app's traffic is low, so always-fresh is cheap.
async function getStore(): Promise<WorkStore> {
  if (await useNeon()) {
    const fromNeon = await neonLoad();
    const s = fromNeon ?? { works: {} };
    if (!s.works) s.works = {};
    return s;
  }
  // Local dev fallback only (no NEON_DB_ANA configured)
  if (!global.__anaWorkStore) {
    global.__anaWorkStore = fileLoad();
  }
  return global.__anaWorkStore;
}

async function mutate(fn: (s: WorkStore) => void): Promise<void> {
  const store = await getStore();
  fn(store);
  if (await useNeon()) {
    await neonSave(store);
  } else {
    global.__anaWorkStore = store;
    fileSave(store);
  }
}

// ─── Work CRUD ────────────────────────────────────────────────────────────────

export async function listWorks(): Promise<ANAWork[]> {
  return Object.values((await getStore()).works).sort((a, b) => b.proposedAt - a.proposedAt);
}

export async function getWork(id: string): Promise<ANAWork | null> {
  return (await getStore()).works[id] ?? null;
}

export async function getActiveWorks(): Promise<ANAWork[]> {
  return (await listWorks()).filter(w => ACTIVE_STATES.includes(w.state));
}

export async function createWork(
  params: Omit<ANAWork, "id" | "votes" | "stateHistory" | "state">,
  initialState: WorkState = "PROPOSED",
): Promise<ANAWork> {
  const id = `work_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const work: ANAWork = {
    ...params,
    id,
    state: initialState,
    votes: [],
    stateHistory: [{ state: initialState, at: Date.now() }],
  };
  await mutate(s => { s.works[id] = work; });
  console.log(`[workStore] created "${work.title}" (${id}) @ ${initialState}`);
  return work;
}

export async function getFoundingWork(): Promise<ANAWork | null> {
  const all = await listWorks();
  return all.find(w => w.isFoundingWork) ?? null;
}

export async function updateWork(id: string, updates: Partial<ANAWork>): Promise<void> {
  await mutate(s => { if (s.works[id]) Object.assign(s.works[id], updates); });
}

export async function advanceState(id: string, newState: WorkState, note?: string): Promise<void> {
  await mutate(s => {
    const w = s.works[id];
    if (!w) return;
    w.state = newState;
    w.stateHistory.push({ state: newState, at: Date.now(), note });
  });
  console.log(`[workStore] ${id} → ${newState}${note ? ` (${note})` : ""}`);
}

export async function addVote(id: string, vote: WorkVote): Promise<void> {
  await mutate(s => {
    const w = s.works[id];
    if (!w) return;
    w.votes = w.votes.filter(v => v.tokenId !== vote.tokenId);
    w.votes.push(vote);
  });
}

// ─── Burn tracking ────────────────────────────────────────────────────────────

export async function getLastNormieSupply(): Promise<number | null> {
  return (await getStore()).lastNormieSupply ?? null;
}

export async function updateNormieSupply(supply: number): Promise<void> {
  await mutate(s => { s.lastNormieSupply = supply; });
}

export async function resetWorks(): Promise<void> {
  const empty: WorkStore = { works: {} };
  if (await useNeon()) {
    await neonSave(empty);
  } else {
    fileSave(empty);
  }
  global.__anaWorkStore = empty;
  console.log("[workStore] reset — all works cleared");
}

// ─── Vote helpers ─────────────────────────────────────────────────────────────

export function hasVoted(work: ANAWork, tokenId: number): boolean {
  return work.votes.some(v => v.tokenId === tokenId);
}

export function tallyVotes(work: ANAWork): {
  yes: number; no: number; abs: number; passed: boolean;
} {
  const yes = work.votes.filter(v => v.vote === "yes").length;
  const no  = work.votes.filter(v => v.vote === "no").length;
  const abs = work.votes.filter(v => v.vote === "abstain").length;
  return { yes, no, abs, passed: yes > no };
}

// ─── HTML builder (on-chain artifact) ────────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function isHtmlArtwork(text: string): boolean {
  const t = text.trimStart();
  return t.startsWith("<!DOCTYPE") || t.startsWith("<html") || t.startsWith("<!doctype");
}

// Fetch a Normie's image and embed as a data URI — permanent on-chain snapshot
// of their appearance at creation time (Normies can change via Canvas later).
//
// KNOWN COST: each PNG is ~18-24KB; embedding 3 (rapporteur+author+curator)
// pushes the certificate to ~110KB base64, which made eth_estimateGas fail
// outright on Base's public RPC when the relayer's balance was too low to
// cover the worst-case gas reservation for a tx this size. Reproduced and
// confirmed at the time via a local simulateContract/estimateContractGas
// script. Re-enabled deliberately now that the relayer balance has been
// topped up — if eth_estimateGas/eth_sendRawTransaction starts failing again
// on publish, suspect this first and fall back to returning `url` directly.
async function fetchNormieImageUri(tokenId: number): Promise<string> {
  const url = `https://api.normies.art/normie/${tokenId}/image.png`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(5_000) });
    if (!res.ok) return url;
    const buf = await res.arrayBuffer();
    const b64 = Buffer.from(buf).toString("base64");
    return `data:image/png;base64,${b64}`;
  } catch {
    return url;
  }
}

/**
 * Builds the governance certificate HTML for WorkRegistry on-chain storage.
 * Always returns a lightweight certificate (~3-8KB) — never the raw artwork.
 *
 * For text/poem works: the artwork is embedded directly in the certificate.
 * For HTML/generative works: the artwork lives in ANAEditions (passed separately
 * to initializeCollection). The certificate only references the collection address.
 * This keeps WorkRegistry content small enough for a single transaction.
 * in WorkRegistry.publish(). No external dependencies, no IPFS.
 * Normie images are embedded as data URIs — snapshot of their appearance at creation time.
 */
export async function buildWorkHtml(work: ANAWork): Promise<string> {
  const [rapporteurImg, authorImg, curatorImg] = await Promise.all([
    work.rapporteurTokenId ? fetchNormieImageUri(work.rapporteurTokenId) : Promise.resolve(""),
    work.authorTokenId     ? fetchNormieImageUri(work.authorTokenId)     : Promise.resolve(""),
    work.curatorTokenId    ? fetchNormieImageUri(work.curatorTokenId)    : Promise.resolve(""),
  ]);

  const yes   = work.yesCount    ?? 0;
  const no    = work.noCount     ?? 0;
  const abs   = work.absCount    ?? 0;
  const total = work.totalVoters ?? Math.max(yes + no + abs, 1);
  const yesPct = Math.round(yes / total * 100);

  const voteRows = (work.votes ?? []).map(v => {
    const icon = v.vote === "yes" ? "✓" : v.vote === "no" ? "✗" : "–";
    const color = v.vote === "yes" ? "var(--y)" : v.vote === "no" ? "var(--n)" : "var(--a)";
    return `<tr><td>${escapeHtml(v.name)}</td><td style="color:${color};text-align:center">${icon}</td><td>${escapeHtml(v.reason)}</td></tr>`;
  }).join("\n");

  const stateLog = (work.stateHistory ?? []).map(h => {
    const d = new Date(h.at).toLocaleDateString("en-GB", {
      day: "2-digit", month: "short", year: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
    return `<div class="entry">▸ <strong>${h.state}</strong> — ${d}${h.note ? ` — ${escapeHtml(h.note)}` : ""}</div>`;
  }).join("\n");

  const proposedDate = new Date(work.proposedAt).toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const publishedDate = work.publishedAt
    ? new Date(work.publishedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
    : "—";

  // For HTML/generative artworks: store a reference to ANAEditions instead of the raw code.
  // The artwork lives in the collection contract — keeping the certificate small (<8KB).
  const artwork = work.artworkText && isHtmlArtwork(work.artworkText)
    ? (work.collectionAddress
        ? `[Generative / visual artwork — stored on-chain in ANAEditions collection ${work.collectionAddress}]`
        : `[Generative / visual artwork — stored on-chain in ANAEditions]`)
    : escapeHtml(work.artworkText ?? "");
  const brief    = escapeHtml(work.brief ?? "");
  const proposal = escapeHtml(work.proposal ?? "");

  const burnNote = work.isBurnMemorial && work.burnedTokenId != null
    ? `<p class="meta" style="color:var(--n);margin-top:.5rem">⬛ Memorial work — Normie #${work.burnedTokenId} burned</p>`
    : "";

  const editionNote = work.editionSupply && work.editionPrice
    ? work.collectionAddress
      ? `<p class="meta" style="color:#a78bfa;margin-top:.3rem">◈ ${work.editionSupply} ERC-721 editions · ${work.editionPrice} ETH · <a href="https://basescan.org/address/${work.collectionAddress}" style="color:#a78bfa;text-decoration:none" target="_blank">${work.collectionAddress}</a></p>`
      : `<p class="meta" style="color:#a78bfa;margin-top:.3rem">◈ ${work.editionSupply} ERC-721 editions · ${work.editionPrice} ETH each</p>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(work.title)} — ANA</title>
<style>
:root{--y:#22c55e;--n:#ef4444;--a:#64748b;--bg:#050505;--s:#0f172a;--t:#e2e8f0;--m:#94a3b8;--b:#1e293b}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--t);font-family:'Courier New',monospace;padding:2rem;max-width:760px;margin:0 auto;line-height:1.6}
h1{font-size:1.4rem;letter-spacing:.08em;margin:.4rem 0}
.sub{color:var(--m);font-size:.65rem;letter-spacing:.15em;text-transform:uppercase}
.meta{color:var(--a);font-size:.75rem;margin-top:.2rem}
section{margin:2rem 0}
.lbl{color:var(--m);font-size:.62rem;text-transform:uppercase;letter-spacing:.18em;border-bottom:1px solid var(--b);padding-bottom:.3rem;margin-bottom:.8rem}
.block{border:1px solid var(--b);padding:1.25rem;white-space:pre-wrap;font-size:.88rem;line-height:1.85}
.vwrap{display:flex;gap:2rem;align-items:flex-start;flex-wrap:wrap;margin-bottom:1rem}
canvas{display:block;flex-shrink:0}
.vleg{font-size:.8rem}.vleg div{margin:.28rem 0}
.vleg .y{color:var(--y)}.vleg .n{color:var(--n)}.vleg .a{color:var(--a)}
.vtab{width:100%;border-collapse:collapse;font-size:.72rem;margin-top:.5rem}
.vtab td{padding:.3rem .45rem;border-bottom:1px solid #111;vertical-align:top}
.vtab td:first-child{color:var(--m);white-space:nowrap;width:30%}
.credits{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.8rem}
.card{border:1px solid var(--b);padding:.7rem;display:flex;flex-direction:column;gap:.4rem}
.card img{width:64px;height:64px;image-rendering:pixelated;display:block}
.card .role{color:var(--m);font-size:.6rem;text-transform:uppercase;letter-spacing:.12em}
.card .name{font-size:.88rem}
.card .cid{color:var(--a);font-size:.68rem}
.log .entry{font-size:.7rem;color:var(--a);padding:.18rem 0;border-bottom:1px solid #0d0d0d}
.log strong{color:var(--t);font-weight:normal}
footer{border-top:1px solid var(--b);padding-top:1rem;margin-top:2rem}
.tx{color:#4ade80;word-break:break-all;font-size:.68rem}
</style>
</head>
<body>
<header>
  <p class="sub">ANA — Agentic Normie Association · Base</p>
  <h1>${escapeHtml(work.title)}</h1>
  <p class="meta">Proposed on ${proposedDate} by ${escapeHtml(work.proposedByName)} · Published on ${publishedDate}</p>
  ${burnNote}
  ${editionNote}
</header>

<section>
<p class="lbl">Initial Proposal</p>
<div class="block">${proposal}</div>
</section>

<section>
<p class="lbl">Assembly Vote — ${work.voteResult === "passed" ? "✓ Approved" : "✗ Rejected"} · ${yesPct}% yes</p>
<div class="vwrap">
<canvas id="vc" width="320" height="170"></canvas>
<div class="vleg">
  <div class="y">✓ Yes&nbsp;: ${yes}</div>
  <div class="n">✗ No&nbsp;: ${no}</div>
  <div class="a">– Abstain&nbsp;: ${abs}</div>
  <div style="margin-top:.5rem;color:#475569">${total} ANA member${total > 1 ? "s" : ""}</div>
</div>
</div>
<table class="vtab">${voteRows}</table>
</section>

<section>
<p class="lbl">Creative Brief — ${escapeHtml(work.rapporteurName ?? "Rapporteur")}</p>
<div class="block">${brief}</div>
</section>

<section>
<p class="lbl">Artwork — ${escapeHtml(work.authorName ?? "Author")}</p>
<div class="block">${artwork}</div>
</section>

<section>
<p class="lbl">Creation Team — snapshot at publication</p>
<div class="credits">
<div class="card">${rapporteurImg ? `<img src="${rapporteurImg}" alt="#${work.rapporteurTokenId}" loading="lazy">` : ""}<div class="role">Rapporteur</div><div class="name">${escapeHtml(work.rapporteurName ?? "—")}</div><div class="cid">#${work.rapporteurTokenId ?? "?"}</div></div>
<div class="card">${authorImg     ? `<img src="${authorImg}"     alt="#${work.authorTokenId}"     loading="lazy">` : ""}<div class="role">Author</div><div class="name">${escapeHtml(work.authorName ?? "—")}</div><div class="cid">#${work.authorTokenId ?? "?"}</div></div>
<div class="card">${curatorImg    ? `<img src="${curatorImg}"    alt="#${work.curatorTokenId}"    loading="lazy">` : ""}<div class="role">Curator</div><div class="name">${escapeHtml(work.curatorName ?? "—")}</div><div class="cid">#${work.curatorTokenId ?? "?"}</div></div>
</div>
</section>

<section>
<p class="lbl">Process Log</p>
<div class="log">${stateLog}</div>
</section>

<footer>
<p class="lbl">On-chain Record</p>
${work.txHash ? `<p class="tx">Base · WorkRegistry · tx: ${work.txHash}</p>` : ""}
<p class="meta" style="margin-top:.5rem">This document is its own certificate of authenticity. Stored immutably on Base. No IPFS.</p>
<p class="meta" style="margin-top:.3rem">ANA operates under the principles of a French loi 1901 cultural association — governed collectively, with no single point of control.</p>
</footer>

<script>
(function(){
  var c=document.getElementById('vc');if(!c)return;
  var ctx=c.getContext('2d');
  var votes=[];
  var yes=${yes},no=${no},abs=${abs};
  for(var i=0;i<yes;i++)votes.push('y');
  for(var i=0;i<no;i++)votes.push('n');
  for(var i=0;i<abs;i++)votes.push('a');
  var cols={y:'#22c55e',n:'#ef4444',a:'#64748b',x:'#1e293b'};
  var cx=160,cy=165,rows=5,rMin=30,rMax=150;
  var idx=0;
  for(var row=0;row<rows;row++){
    var r=rMin+(rMax-rMin)*(row/(rows-1));
    var nDots=Math.max(3,Math.round(Math.PI*r/8));
    for(var d=0;d<nDots;d++){
      var angle=Math.PI+(Math.PI*d/(nDots-1));
      var x=cx+r*Math.cos(angle);
      var y=cy+r*Math.sin(angle);
      ctx.beginPath();ctx.arc(x,y,2.6,0,6.283);
      ctx.fillStyle=cols[votes[idx]||'x'];ctx.fill();
      idx++;
    }
  }
})();
</script>
</body>
</html>`;
}
