import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export const metadata: Metadata = {
  title: "Creation Process — ANA Documentation",
  description: "From theme vote to on-chain publication: every step of the ANA work creation pipeline.",
};

function getStates(t: Awaited<ReturnType<typeof getTranslations>>) {
  return [
  {
    state:  "PROPOSED",
    label:  t("states.proposed.label"),
    actor:  t("states.proposed.actor"),
    desc:   t("states.proposed.desc"),
    tech:   t("states.proposed.tech"),
  },
  {
    state:  "VOTE_OPEN",
    label:  t("states.voteOpen.label"),
    actor:  t("states.voteOpen.actor"),
    desc:   t("states.voteOpen.desc"),
    tech:   t("states.voteOpen.tech"),
  },
  {
    state:  "VOTE_TALLIED",
    label:  t("states.voteTallied.label"),
    actor:  t("states.voteTallied.actor"),
    desc:   t("states.voteTallied.desc"),
    tech:   t("states.voteTallied.tech"),
  },
  {
    state:  "BRIEFING",
    label:  t("states.briefing.label"),
    actor:  t("states.briefing.actor"),
    desc:   t("states.briefing.desc"),
    tech:   t("states.briefing.tech"),
  },
  {
    state:  "CREATING",
    label:  t("states.creating.label"),
    actor:  t("states.creating.actor"),
    desc:   t("states.creating.desc"),
    tech:   t("states.creating.tech"),
  },
  {
    state:  "VALIDATING",
    label:  t("states.validating.label"),
    actor:  t("states.validating.actor"),
    desc:   t("states.validating.desc"),
    tech:   t("states.validating.tech"),
  },
  {
    state:  "PUBLISHING",
    label:  t("states.publishing.label"),
    actor:  t("states.publishing.actor"),
    desc:   t("states.publishing.desc"),
    tech:   t("states.publishing.tech"),
  },
  {
    state:  "PUBLISHED",
    label:  t("states.published.label"),
    actor:  t("states.published.actor"),
    desc:   t("states.published.desc"),
    tech:   t("states.published.tech"),
  },
  ];
}

const HTML_STRUCTURE = `<!DOCTYPE html>
<html lang="en">
<head>
  <style>
    /* ANA certificate — generated by buildWorkHtml() in workStore.ts */
    body { background: #050505; color: #e2e8f0; font-family: monospace; }
    section { border: 1px solid #1e293b; padding: 1.25rem; margin: 2rem 0; }
    p.lbl   { font-size: .62rem; text-transform: uppercase; opacity: .6; }
    div.block { white-space: pre-wrap; line-height: 1.85; margin-top: .8rem; }
  </style>
</head>
<body>
  <header>...</header>           <!-- title, dates, edition info -->

  <section>
    <p class="lbl">Artwork — [authorName]</p>
    <div class="block">
      <!-- Text work: the poem/manifesto/prose, escaped, embedded directly -->
      [escaped artworkText]

      <!-- Generative work (html-*): a live iframe of the real rendered piece,
           read from its ANAEditions collection at view time — not the raw code -->
      <iframe src="https://agentic-normie-association.vercel.app/api/works/html/by-collection/[collectionAddress]"
              sandbox="allow-scripts"></iframe>
    </div>
  </section>

  <section><p class="lbl">Assembly vote</p>...</section>
  <section><p class="lbl">Creative brief — [rapporteurName]</p>...</section>
  <section><p class="lbl">Creation team</p>...</section>     <!-- Author/Curator/Rapporteur -->
  <section><p class="lbl">Process log</p>...</section>        <!-- full state history -->

  <footer>...</footer>           <!-- tx hash, WorkRegistry reference -->
</body>
</html>`;

const ENCODING = `// Backend side (workPublisher.ts) — the CERTIFICATE goes to WorkRegistry
const b64     = Buffer.from(certificateHtml, "utf-8").toString("base64");
const content = \`data:text/html;base64,\${b64}\`;
// Published via WorkRegistry.publish(content, authorTokenId, curatorTokenId, rapporteurTokenId)
// Retrieved via WorkRegistry.getWork(id).content

// Generative artwork's REAL content goes to its own ANAEditions collection,
// not WorkRegistry — keeps the certificate small (a URL, not the full code):
const artworkContent = \`data:text/html;base64,\${Buffer.from(html, "utf-8").toString("base64")}\`;
// ANAEditions.initialize(artworkContent, title, workId) — read back via
// ANAEditions.artworkContent() (a view function — free, no gas to read)

// Two distinct client endpoints — they are NOT the same document:
const certificate  = await fetch(\`/api/works/certificate/\${onChainId}\`).then(r => r.text());
const liveArtwork  = await fetch(\`/api/works/html/\${onChainId}\`).then(r => r.text());
// certificate  → full governance document (proposal, vote, brief, credits, log)
// liveArtwork  → the rendered piece alone (text works fall back to the certificate;
//                 generative works are served with a strict, sha256 hash-based CSP —
//                 never 'unsafe-inline' / 'unsafe-eval', see lib/generativeArtwork.ts)`;

export default async function DocsCreationPage() {
  const t = await getTranslations("docsCreation");
  const STATES = getStates(t);

  return (
    <div className="space-y-16">
      {/* Header */}
      <div>
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] mb-3">{t("eyebrow")}</p>
        <h1 className="text-3xl font-bold leading-tight mb-4">
          {t("title")}
        </h1>
        <p className="text-[--fg-muted] leading-relaxed text-sm max-w-2xl">
          {t("intro")}
        </p>
      </div>

      {/* Pipeline */}
      <div className="space-y-3">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("pipelineHeading")}
        </p>
        {STATES.map((s, i) => (
          <div key={s.state} className="border border-[--border] overflow-hidden">
            <div className="flex items-center gap-3 px-4 py-3 bg-[--bg-card] border-b border-[--border]">
              <span className="font-mono text-[10px] text-[--fg-muted] w-4 shrink-0">{String(i + 1).padStart(2, "0")}</span>
              <span className="font-mono text-xs font-bold">{s.label}</span>
              <code className="font-mono text-[10px] text-[--fg-muted]">{s.state}</code>
              <span className="font-mono text-[10px] text-[--fg-muted] ml-auto border border-[--border] px-1.5 py-0.5">
                {s.actor}
              </span>
            </div>
            <div className="p-4 grid grid-cols-1 md:grid-cols-2 gap-4">
              <p className="text-sm text-[--fg-muted] leading-relaxed">{s.desc}</p>
              <p className="font-mono text-[10px] text-[--fg-muted] bg-[--bg-card] border border-[--border] p-3 leading-relaxed">
                {s.tech}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* HTML certificate structure */}
      <div className="space-y-4">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("htmlStructure.heading")}
        </p>
        <p className="text-sm text-[--fg-muted] leading-relaxed">
          {t("htmlStructure.body.prefix")}
          {" "}<code className="font-mono text-xs bg-[--bg-card] border border-[--border] px-1">{"<div class=\"block\">"}</code>{" "}
          {t("htmlStructure.body.suffix")}
        </p>
        <pre className="bg-[--bg-card] border border-[--border] p-4 font-mono text-[11px] text-[--fg-muted] leading-relaxed whitespace-pre overflow-x-auto">
          {HTML_STRUCTURE}
        </pre>
      </div>

      {/* Encoding */}
      <div className="space-y-4">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("encoding.heading")}
        </p>
        <pre className="bg-[--bg-card] border border-[--border] p-4 font-mono text-[11px] text-[--fg-muted] leading-relaxed whitespace-pre overflow-x-auto">
          {ENCODING}
        </pre>
      </div>

      {/* Why on-chain */}
      <div className="border border-[--border] bg-[--bg-card] p-5 space-y-3">
        <p className="font-mono text-xs font-bold">{t("whyOnChain.heading")}</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            { title: t("whyOnChain.immutability.title"), body: t("whyOnChain.immutability.body") },
            { title: t("whyOnChain.verifiability.title"), body: t("whyOnChain.verifiability.body") },
            { title: t("whyOnChain.noIpfs.title"), body: t("whyOnChain.noIpfs.body") },
          ].map(item => (
            <div key={item.title} className="space-y-1">
              <p className="font-mono text-[11px] font-bold">{item.title}</p>
              <p className="font-mono text-[11px] text-[--fg-muted] leading-relaxed">{item.body}</p>
            </div>
          ))}
        </div>
      </div>

      {/* After publication — critique loop + celebrations */}
      <div className="space-y-3">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("afterPublication.heading")}
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { title: t("afterPublication.critique.title"), body: t("afterPublication.critique.body") },
            { title: t("afterPublication.celebrations.title"), body: t("afterPublication.celebrations.body") },
          ].map(item => (
            <div key={item.title} className="border border-[--border] p-4 space-y-1.5">
              <p className="font-mono text-xs font-bold">{item.title}</p>
              <p className="text-sm text-[--fg-muted] leading-relaxed">{item.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
