import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export const metadata: Metadata = {
  title: "Creation Process — ANA Documentation",
  description: "From theme vote to on-chain publication: every step of the ANA work creation pipeline.",
};

function getStates(t: Awaited<ReturnType<typeof getTranslations>>) {
  return [
  {
    state:  "PROPOSED",
    label:  t("states.proposed.label"),
    actor:  t("states.proposed.actor"),
    desc:   t("states.proposed.desc"),
    tech:   t("states.proposed.tech"),
  },
  {
    state:  "VOTE_OPEN",
    label:  t("states.voteOpen.label"),
    actor:  t("states.voteOpen.actor"),
    desc:   t("states.voteOpen.desc"),
    tech:   t("states.voteOpen.tech"),
  },
  {
    state:  "BRIEFING",
    label:  t("states.briefing.label"),
    actor:  t("states.briefing.actor"),
    desc:   t("states.briefing.desc"),
    tech:   t("states.briefing.tech"),
  },
  {
    state:  "CREATING",
    label:  t("states.creating.label"),
    actor:  t("states.creating.actor"),
    desc:   t("states.creating.desc"),
    tech:   t("states.creating.tech"),
  },
  {
    state:  "VALIDATING",
    label:  t("states.validating.label"),
    actor:  t("states.validating.actor"),
    desc:   t("states.validating.desc"),
    tech:   t("states.validating.tech"),
  },
  {
    state:  "PUBLISHING",
    label:  t("states.publishing.label"),
    actor:  t("states.publishing.actor"),
    desc:   t("states.publishing.desc"),
    tech:   t("states.publishing.tech"),
  },
  {
    state:  "PUBLISHED",
    label:  t("states.published.label"),
    actor:  t("states.published.actor"),
    desc:   t("states.published.desc"),
    tech:   t("states.published.tech"),
  },
  ];
}

const HTML_STRUCTURE = `<!DOCTYPE html>
<html lang="en">
<head>
  <style>
    /* ANA certificate — style generated by buildWorkHtml() */
    body.certificat { background: #050505; color: #e2e8f0; font-family: monospace; }
    section { border: 1px solid #2d2d2d; padding: 1.5rem; margin: 1rem 0; }
    p.lbl   { font-size: .65rem; text-transform: uppercase; opacity: .5; }
    div.block { white-space: pre-wrap; line-height: 1.7; margin-top: .75rem; }
  </style>
</head>
<body class="certificat">
  <!-- Header: title, date, theme -->
  <header>...</header>

  <!-- Work section (the poem / the script) -->
  <section>
    <p class="lbl">Work — [authorName]</p>
    <div class="block">[artworkText or <script>...]</div>
  </section>

  <!-- Creative trio section -->
  <section>
    <p class="lbl">Author · Curator · Rapporteur</p>
    ...
  </section>

  <!-- Footer: transaction hash, WorkRegistry address -->
  <footer>...</footer>
</body>
</html>`;

const ENCODING = `// Backend side (workPublisher.ts)
const b64     = Buffer.from(htmlContent, "utf-8").toString("base64");
const content = \`data:text/html;base64,\${b64}\`;

// Published on-chain via WorkRegistry.publish(content, ...)
// Retrieved on-chain via WorkRegistry.getWork(id).content

// Client side (WorksClient.tsx) — extract the poem
const html    = await fetch(\`/api/works/html/\${onChainId}\`).then(r => r.text());
const doc     = new DOMParser().parseFromString(html, "text/html");
const section = Array.from(doc.querySelectorAll("section"))
  .find(s => s.querySelector(".lbl")?.textContent?.startsWith("Work"));
const poem    = section?.querySelector(".block")?.textContent?.trim();`;

export default async function DocsCreationPage() {
  const t = await getTranslations("docsCreation");
  const STATES = getStates(t);

  return (
    <div className="space-y-16">
      {/* Header */}
      <div>
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] mb-3">{t("eyebrow")}</p>
        <h1 className="text-3xl font-bold leading-tight mb-4">
          {t("title")}
        </h1>
        <p className="text-[--fg-muted] leading-relaxed text-sm max-w-2xl">
          {t("intro")}
        </p>
      </div>

      {/* Pipeline */}
      <div className="space-y-3">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("pipelineHeading")}
        </p>
        {STATES.map((s, i) => (
          <div key={s.state} className="border border-[--border] overflow-hidden">
            <div className="flex items-center gap-3 px-4 py-3 bg-[--bg-card] border-b border-[--border]">
              <span className="font-mono text-[10px] text-[--fg-muted] w-4 shrink-0">{String(i + 1).padStart(2, "0")}</span>
              <span className="font-mono text-xs font-bold">{s.label}</span>
              <code className="font-mono text-[10px] text-[--fg-muted]">{s.state}</code>
              <span className="font-mono text-[10px] text-[--fg-muted] ml-auto border border-[--border] px-1.5 py-0.5">
                {s.actor}
              </span>
            </div>
            <div className="p-4 grid grid-cols-1 md:grid-cols-2 gap-4">
              <p className="text-sm text-[--fg-muted] leading-relaxed">{s.desc}</p>
              <p className="font-mono text-[10px] text-[--fg-muted] bg-[--bg-card] border border-[--border] p-3 leading-relaxed">
                {s.tech}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* HTML certificate structure */}
      <div className="space-y-4">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("htmlStructure.heading")}
        </p>
        <p className="text-sm text-[--fg-muted] leading-relaxed">
          {t("htmlStructure.body.prefix")}
          {" "}<code className="font-mono text-xs bg-[--bg-card] border border-[--border] px-1">{"<div class=\"block\">"}</code>{" "}
          {t("htmlStructure.body.suffix")}
        </p>
        <pre className="bg-[--bg-card] border border-[--border] p-4 font-mono text-[11px] text-[--fg-muted] leading-relaxed whitespace-pre overflow-x-auto">
          {HTML_STRUCTURE}
        </pre>
      </div>

      {/* Encoding */}
      <div className="space-y-4">
        <p className="font-mono text-[10px] uppercase tracking-widest text-[--fg-muted] border-b border-[--border] pb-2">
          {t("encoding.heading")}
        </p>
        <pre className="bg-[--bg-card] border border-[--border] p-4 font-mono text-[11px] text-[--fg-muted] leading-relaxed whitespace-pre overflow-x-auto">
          {ENCODING}
        </pre>
      </div>

      {/* Why on-chain */}
      <div className="border border-[--border] bg-[--bg-card] p-5 space-y-3">
        <p className="font-mono text-xs font-bold">{t("whyOnChain.heading")}</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            { title: t("whyOnChain.immutability.title"), body: t("whyOnChain.immutability.body") },
            { title: t("whyOnChain.verifiability.title"), body: t("whyOnChain.verifiability.body") },
            { title: t("whyOnChain.noIpfs.title"), body: t("whyOnChain.noIpfs.body") },
          ].map(item => (
            <div key={item.title} className="space-y-1">
              <p className="font-mono text-[11px] font-bold">{item.title}</p>
              <p className="font-mono text-[11px] text-[--fg-muted] leading-relaxed">{item.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
