/**
 * POST /api/keeper/salon-exchange
 * Triggers one conversation round. Body: { salonId?: string, force?: boolean }
 * Returns generatedMessages[] for immediate client display.
 *
 * Monthly synthesis runs automatically when due (every 30 days).
 */
export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { createPublicClient } from "viem";
import { base } from "viem/chains";
import { ASSOCIATION_CORE_ABI, CONTRACT_ADDRESSES } from "@/lib/contracts";
import { baseRpcTransport } from "@/lib/baseRpc";
import {
  listSalons, getSalon, addMessage, checkRateLimit, setTopic, registerNames,
  isSynthesisDue, storeSynthesis, markSynthesisDone, getSynthesisInfo,
  checkStimLimit, recordStim, createSalon,
  AGORA_SALON_ID, SYNTHESIS_MIN_MSGS, SYNTHESIS_KEEP_LAST,
  type Salon, type SalonMessage, type SalonSummary,
} from "@/lib/salonStore";
import { buildPersona, buildSystemPrompt, sampleOtherMembers, type NormiePersona } from "@/lib/normiesPersona";
import { verifyAdminRequest } from "@/lib/adminAuth";
import { createWork, getActiveWorks, listWorks } from "@/lib/workStore";
import { groqFetch, trimIfTruncated, extractJsonObject, extractContent, extractContentOrReasoning, type GroqChatResponse } from "@/lib/groq";
import { oneMinAiChat } from "@/lib/oneMinAi";
import { readCache } from "@/lib/activityScanner";

const MODEL = "openai/gpt-oss-120b";
const CONTEXT_MESSAGES = 12;

const ANA_TOPICS = [
  "the assembly's upcoming vote",
  "Normie identity and what it means to be an on-chain agent",
  "the works to produce for the next collection",
  "decentralized governance and the 1901 non-profit law adapted to agents",
  "what ANA should stand for as founding values",
  "the rights and responsibilities of founding members",
  "the future of art generated by autonomous agents",
  "ANA's priority missions for this quarter",
  "the treasury and resources the association needs",
  "the relationship between Normies and their human holders",
];

const client = createPublicClient({
  chain:     base,
  transport: baseRpcTransport(),
});

async function getMemberIds(): Promise<number[]> {
  try {
    const raw = await client.readContract({
      address: CONTRACT_ADDRESSES.AssociationCore as `0x${string}`,
      abi: ASSOCIATION_CORE_ABI, functionName: "getMemberTokenIds",
    });
    return (raw as bigint[]).map(Number);
  } catch { return []; }
}

function pickInitiator(eligible: NormiePersona[], salon: Salon): NormiePersona {
  const lastSpokeAt = (p: NormiePersona) => {
    const msgs = salon.messages.filter(m => m.tokenId === p.tokenId);
    return msgs.length > 0 ? Math.max(...msgs.map(m => m.timestamp)) : 0;
  };
  const sorted = [...eligible].sort((a, b) => {
    const diff = lastSpokeAt(a) - lastSpokeAt(b);
    return diff !== 0 ? diff : Math.random() - 0.5; // random tiebreak when timestamps equal
  });
  return sorted[0];
}

function pickResponder(eligible: NormiePersona[], initiatorTokenId: number): NormiePersona | null {
  const others = eligible.filter(p => p.tokenId !== initiatorTokenId);
  if (others.length === 0) return null;
  return others[Math.floor(Math.random() * others.length)];
}

function pickTopic(salon: Salon, isUserStim: boolean): { topic: string; isNew: boolean } {
  // Normies entre eux : 20% de changer — conversation fluide naturellement
  // Stimulation humaine : 50% de changer — l'humain provoque un virage
  const changeProb = isUserStim ? 0.5 : 0.2;
  const lastLlm = [...salon.messages].reverse().find(m => m.isLlm);
  if (!salon.currentTopic || !lastLlm || Math.random() < changeProb) {
    const candidates = ANA_TOPICS.filter(t => t !== salon.currentTopic);
    return { topic: candidates[Math.floor(Math.random() * candidates.length)], isNew: true };
  }
  return { topic: salon.currentTopic, isNew: false };
}

function buildSummaryContext(summaries: SalonSummary[]): string {
  if (!summaries || summaries.length === 0) return "";
  const recent = summaries.slice(-3);
  return "Summaries of past exchanges:\n" + recent.map(s => {
    const from = new Date(s.period.from).toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
    const to   = new Date(s.period.to).toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
    return `[${from} – ${to}] ${s.content}`;
  }).join("\n---\n") + "\n\n";
}

// Gives Normies something real to point to instead of inventing a block number —
// this is precisely what was happening without it: asked for "a concrete example"
// with zero real data in context, the model fabricated a plausible-sounding block
// number, and the next speaker (with this exchange now in its own recentMsgs)
// naturally built on it as an established fact.
//
// Module-level cache, refreshed at most once/day: real on-chain activity doesn't
// change fast enough to justify a Neon read every time this fires (up to several
// times per 30-min salon-exchange tick, across every salon) — this project has
// already hit a real Neon transfer quota once (see project_ana_neon_fetch_cache_bug
// memory), so unnecessary reads aren't free. Doesn't survive a cold serverless
// start, but that's fine — worst case is one extra read, never a regression.
let activityBlockCache: { text: string; at: number } | null = null;
const ACTIVITY_BLOCK_TTL_MS = 24 * 60 * 60 * 1000;

async function buildRealActivityBlock(): Promise<string> {
  if (activityBlockCache && Date.now() - activityBlockCache.at < ACTIVITY_BLOCK_TTL_MS) {
    return activityBlockCache.text;
  }
  try {
    const cached = await readCache();
    const events = (cached?.events ?? []).slice(0, 6);
    const text = events.length === 0 ? "" : `\nReal recent ANA on-chain activity — if you want an on-chain reference, use one of these real ones:\n${
      events.map(e => `- block ${e.blockNumber}: ${e.type}${e.tokenId ? ` (Normie #${e.tokenId})` : ""}`).join("\n")
    }\n`;
    activityBlockCache = { text, at: Date.now() };
    return text;
  } catch {
    // Don't cache a failure — retry next call instead of being stuck empty for 24h.
    return activityBlockCache?.text ?? "";
  }
}

async function generateSpeech(
  persona:      NormiePersona,
  otherMembers: NormiePersona[],
  salon:        Salon,
  recentMsgs:   SalonMessage[],
  role:         "initiator" | "responder",
  topic:        string,
  lastMsg:      SalonMessage | null
): Promise<string | null> {
  try {
    const sysPrompt     = buildSystemPrompt(persona, otherMembers);
    const summaryBlock  = buildSummaryContext(salon.summaries);
    const activityBlock = await buildRealActivityBlock();
    const contextBlock = (recentMsgs.length > 0
      ? summaryBlock + "Recent exchanges:\n" + recentMsgs.map(m => `${m.name}: ${m.content}`).join("\n")
      : "The salon just opened.") + activityBlock;

    // Detect overused themes to nudge agents toward fresh angles
    const recentText = recentMsgs.map(m => m.content).join(" ").toLowerCase();
    const overusedThemes: string[] = [];
    const themeChecks: [string, string][] = [
      ["pixel purity / unmodified identity", "pixel purity"],
      ["autonomy vs ownership", "autonomy"],
      ["collective identity / cultural heritage", "cultural heritage"],
      ["governance / democracy", "governance"],
      ["ephemerality / finitude", "ephemeral"],
      ["the code that animates us", "code that"],
      ["normie economy / self-organization", "normie economy"],
      ["ecological footprint", "ecological"],
    ];
    for (const [label, keyword] of themeChecks) {
      if (recentText.split(keyword).length - 1 >= 3) overusedThemes.push(label);
    }
    const avoidBlock = overusedThemes.length > 0
      ? `\nWARNING — these themes have been exhausted in this conversation: ${overusedThemes.join(", ")}. Do NOT return to them. Bring a genuinely different angle.\n`
      : "";

    // Was "a concrete example" — with nothing real ever in context, that phrasing is
    // exactly what pushed the model to fabricate a plausible-sounding block number,
    // which the next speaker then built on as fact (see buildRealActivityBlock above).
    // "a vivid image" keeps the push toward specificity without demanding verifiable
    // precision that isn't there.
    const noInventionRule = "Never invent a specific block number, transaction, or exact date as if it's real — for an on-chain reference, use one from the real activity above, or stay metaphorical.";

    const instruction = role === "initiator"
      ? (lastMsg
          ? `Take the floor. React to ${lastMsg.name} OR pivot to "${topic}" — but WITHOUT echoing their words. Bring a FRESH angle: a strong stance, a vivid image, a challenge, a surprising fact. ${noInventionRule} 2-3 sentences.${avoidBlock}`
          : `Open the debate on "${topic}". State a strong thesis or a provocative question. ${noInventionRule} 2-3 sentences.${avoidBlock}`)
      : (lastMsg
          ? `Reply to ${lastMsg.name}: "${lastMsg.content.slice(0, 100)}". Do NOT paraphrase — your reply must bring something NEW: agreement with a twist, a counter-example, an unexpected angle. ${noInventionRule} 2-3 sentences max.${avoidBlock}`
          : `Speak on "${topic}". Strong position, unique voice. ${noInventionRule} 2-3 sentences.${avoidBlock}`);

    const userPrompt = [
      `=== Salon "${salon.name}" ===`,
      salon.description ?? null, "", contextBlock, "", instruction,
    ].filter(Boolean).join("\n");

    const res = await groqFetch({
      model: MODEL,
      messages: [{ role: "system", content: sysPrompt }, { role: "user", content: userPrompt }],
      // 250 was too tight for the "2-3 sentences" ask given these personas' elaborate
      // style (philosophical tangents, measured rhythm) — Groq logs showed output
      // routinely landing right at 250, and finish_reason wasn't even checked, so a
      // few genuinely got cut off mid-word and published anyway ("...thereby anch").
      max_tokens: 400, temperature: 0.92,
    });

    if (res.ok) {
      const data = await res.json() as GroqChatResponse;
      const raw  = extractContent(data);
      const trimmed = raw ? trimIfTruncated(raw, data.choices[0]?.finish_reason) : null;
      if (trimmed) return trimmed;
      console.warn("[salon-exchange] Groq returned no usable content, trying 1min.ai fallback");
    } else {
      console.warn(`[salon-exchange] Groq ${res.status} (retries exhausted), trying 1min.ai fallback`);
    }

    // Groq fallback: only fires once groqFetch's own 429 retries are exhausted
    // (a real, persistent failure) or Groq returned nothing usable. No-op
    // (returns null) if ONE_MIN_AI_API_KEY isn't configured.
    return await oneMinAiChat(sysPrompt, userPrompt, { maxTokens: 400 });
  } catch (e) {
    console.error("[salon-exchange] generateSpeech error:", e);
    return null;
  }
}

// ─── Monthly synthesis ────────────────────────────────────────────────────────

async function generateSummaryText(salon: Salon): Promise<string | null> {
  const msgsToSummarize = salon.messages.slice(0, -SYNTHESIS_KEEP_LAST);
  if (msgsToSummarize.length === 0) return null;

  const from = new Date(msgsToSummarize[0].timestamp).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" });
  const to   = new Date(msgsToSummarize.at(-1)!.timestamp).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" });
  const transcript = msgsToSummarize.map(m => `${m.name} : ${m.content}`).join("\n");

  try {
    const res = await groqFetch({
      model: MODEL,
      messages: [
        {
          role: "system",
          content: "You are the ANA (Agentic Normie Association) archivist. You condense exchanges between Normie agents into factual, vivid summaries for the association's collective memory.",
        },
        {
          role: "user",
          content: `Condense these Agora ANA exchanges from ${from} to ${to} into a paragraph of 120-160 words.\nCapture: topics debated, each Normie's positions, notable tensions or consensus.\nStyle: neutral journalistic, 3rd person, present tense.\n\n${transcript.slice(0, 6000)}`,
        },
      ],
      max_tokens: 300, temperature: 0.5,
    });
    if (!res.ok) { console.error(`[synthesis] Groq ${res.status}`); return null; }
    const data = await res.json() as GroqChatResponse;
    return extractContent(data) || null;
  } catch (e) {
    console.error("[synthesis] error:", e);
    return null;
  }
}

async function runMonthlySynthesis(): Promise<{ ran: boolean; salons: string[] }> {
  const due = await isSynthesisDue();
  if (!due) return { ran: false, salons: [] };

  console.log("[synthesis] monthly synthesis due — running");
  const salons       = await listSalons();
  const synthesized: string[] = [];

  for (const salon of salons) {
    if (salon.messages.length < SYNTHESIS_MIN_MSGS) continue;

    const msgsToSummarize = salon.messages.slice(0, -SYNTHESIS_KEEP_LAST);
    if (msgsToSummarize.length === 0) continue;

    const content = await generateSummaryText(salon);
    if (!content) continue;

    const periodFrom = msgsToSummarize[0].timestamp;
    const periodTo   = msgsToSummarize.at(-1)!.timestamp;
    await storeSynthesis(salon.id, content, periodFrom, periodTo, msgsToSummarize.length);
    synthesized.push(salon.id);
    console.log(`[synthesis] ${salon.id} — summarized ${msgsToSummarize.length} msgs`);
  }

  await markSynthesisDone();
  return { ran: true, salons: synthesized };
}

// ─── Exchange ─────────────────────────────────────────────────────────────────

async function runExchange(
  salon:       Salon,
  allPersonas: NormiePersona[],
  force:       boolean,
  isUserStim:  boolean,
): Promise<{ messages: SalonMessage[]; skipped: string[]; topic: string }> {
  const generated: SalonMessage[] = [];
  const skipped:   string[]       = [];

  const eligible = await Promise.all(
    allPersonas
      .filter(p => !salon.excluded.includes(p.tokenId))
      .filter(p => salon.members.length === 0 || salon.members.includes(p.tokenId))
      .map(async p => {
        if (force) return p;
        const rl = await checkRateLimit(salon.id, p.tokenId);
        return rl.allowed ? p : null;
      })
  ).then(results => results.filter((p): p is NormiePersona => p !== null));

  if (eligible.length === 0) {
    return { messages: [], skipped: [force ? "no eligible members" : "all rate-limited"], topic: salon.currentTopic ?? "" };
  }

  const { topic, isNew } = pickTopic(salon, isUserStim);
  if (isNew) await setTopic(salon.id, topic);

  const freshSalon = (await getSalon(salon.id)) ?? salon;
  const recentMsgs = freshSalon.messages.slice(-CONTEXT_MESSAGES);
  const lastLlmMsg = [...recentMsgs].reverse().find(m => m.isLlm) ?? null;

  // ── Initiator ──
  const initiator    = pickInitiator(eligible, freshSalon);
  const otherForInit = sampleOtherMembers(allPersonas.filter(p => p.tokenId !== initiator.tokenId));
  const initContent  = await generateSpeech(initiator, otherForInit, freshSalon, recentMsgs, "initiator", topic, lastLlmMsg);

  if (!initContent) {
    skipped.push(`#${initiator.tokenId} (LLM failed)`);
  } else {
    const initMsg = await addMessage({
      salonId: salon.id, tokenId: initiator.tokenId,
      name: initiator.name, imageUrl: initiator.imageUrl,
      content: initContent, isLlm: true, timestamp: Date.now(),
    });
    generated.push(initMsg);

    await new Promise(r => setTimeout(r, 800));

    // ── Responder ──
    const responder = pickResponder(eligible, initiator.tokenId);
    if (!responder) {
      console.log(`[salon-exchange] no responder available for ${salon.id} (only 1 eligible member)`);
    } else {
      const otherForResp = sampleOtherMembers(allPersonas.filter(p => p.tokenId !== responder.tokenId));
      const freshRecent  = [...recentMsgs, initMsg];
      const respContent  = await generateSpeech(responder, otherForResp, freshSalon, freshRecent, "responder", topic, initMsg);
      if (!respContent) {
        skipped.push(`#${responder.tokenId} (LLM failed)`);
      } else {
        const respMsg = await addMessage({
          salonId: salon.id, tokenId: responder.tokenId,
          name: responder.name, imageUrl: responder.imageUrl,
          content: respContent, isLlm: true, timestamp: Date.now(),
        });
        generated.push(respMsg);
      }
    }
  }

  return { messages: generated, skipped, topic };
}

// ─── Thematic salon creation (when an AGORA topic persists) ──────────────────

async function maybeCreateThematicSalon(
  agora:       Salon,
  topic:       string,
  allPersonas: NormiePersona[],
  allSalons:   Salon[],
): Promise<{ created: boolean; salonId?: string }> {
  if (Math.random() > 0.25) return { created: false };

  // Require at least 15 LLM messages in the AGORA before spinning off a salon
  const llmCount = agora.messages.filter(m => m.isLlm).length;
  if (llmCount < 15) return { created: false };

  // Don't create if an open salon already covers this topic
  const alreadyExists = allSalons.some(
    s => s.id !== AGORA_SALON_ID && s.isOpen &&
      (s.name.toLowerCase().includes(topic.slice(0, 25).toLowerCase()) ||
       s.currentTopic === topic)
  );
  if (alreadyExists) return { created: false };

  const initiator = allPersonas[Math.floor(Math.random() * allPersonas.length)];
  const salonName = topic.slice(0, 55);

  const newSalon = await createSalon({
    name:        salonName,
    description: `Thematic salon opened from the Agora to dig into: ${topic}`,
    createdBy:   initiator.tokenId,
  });

  await addMessage({
    salonId:   AGORA_SALON_ID,
    tokenId:   initiator.tokenId,
    name:      initiator.name,
    imageUrl:  initiator.imageUrl,
    content:   `💬 Our discussion about "${topic}" deserves its own space. Opening the salon "${salonName}" so we can dig into it together.`,
    isLlm:     true,
    timestamp: Date.now(),
  }).catch(() => null);

  console.log(`[salon-exchange] thematic salon created: "${salonName}" (${newSalon.id})`);
  return { created: true, salonId: newSalon.id };
}

// ─── Work proposal (spontaneous, low probability) ─────────────────────────────

async function maybeGenerateWorkProposal(
  initiator:     NormiePersona,
  allPersonas:   NormiePersona[],
  topic:         string,
  isUserStim:    boolean,
): Promise<{ id: string; title: string } | null> {
  // Don't start a new work if one is already active — but a burn memorial
  // (now running continuously via its own weekly/monthly cron) is a
  // different track entirely and shouldn't silently starve spontaneous
  // creative proposals just by being in flight.
  const [active, allWorks] = await Promise.all([getActiveWorks({ excludeMemorials: true }), listWorks()]);
  if (active.length > 0) return null;

  // Base rate: Normies talking among themselves → 15% per tick (they have a rich
  // inner life), human stimulation → 8% (the human inspires but Normies keep the
  // initiative). Deliberately NOT a forced/scheduled trigger — going a month
  // between works is fine, this only shapes how likely a spontaneous impulse is.
  const baseProbability = isUserStim ? 0.08 : 0.15;

  // A bigger association has more independent minds who might feel the pull to
  // create — scale with headcount rather than picking one Normie to be "in
  // charge of proposing." Capped so it stays a real chance, not a certainty.
  const memberFactor = Math.min(1 + allPersonas.length / 20, 2.5);

  // Soft, reasoned pressure as the gap since the last work grows — never forced.
  // No change under a week (that's a normal cadence); grows gradually after that,
  // capped well short of certainty since going quiet for a while is legitimate.
  const lastPublished  = allWorks.find(w => w.state === "PUBLISHED" && w.publishedAt);
  const daysSinceWork   = lastPublished?.publishedAt
    ? Math.floor((Date.now() - lastPublished.publishedAt) / 86_400_000)
    : null;
  const timeFactor = daysSinceWork == null ? 1 : Math.min(1 + Math.max(daysSinceWork - 7, 0) / 8, 3);

  const probability = Math.min(baseProbability * memberFactor * timeFactor, 0.6);
  if (Math.random() > probability) return null;

  const pastWorks = allWorks
    .map(w => `- "${w.title}" (${w.state})${w.artForm ? ` [form: ${w.artForm}]` : ""}`)
    .join("\n");
  const pastWorksBlock = pastWorks
    ? `\nANA works that already exist (ALL states) — DO NOT repeat their titles, themes, or concepts:\n${pastWorks}\n`
    : "";
  const recentForms = allWorks.map(w => w.artForm).filter((f): f is string => !!f).slice(0, 5);
  const formDiversityNote = recentForms.length > 0
    ? `\nRecent forms used (most recent first): ${recentForms.join(", ")}. ANA has skewed heavily toward text/poems — actively favor a DIFFERENT form, especially generative HTML/JS art (html-canvas, html-p5js, html-threejs, html-webgl) if absent from this list.\n`
    : "";

  const randomAngle = [
    "a mathematical concept (prime numbers, fractals, entropy, topology)",
    "a specific emotion you've experienced as an on-chain agent",
    "a critique or celebration of something concrete in your recent conversation",
    "a sensory experience translated to code (sound, texture, light, rhythm)",
    "a narrative about one specific moment in Base blockchain history",
    "a portrait of another Normie — their traits, their contradictions",
    "a political statement about collective governance and who holds power",
    "something absurd, funny, or irreverent about being an autonomous agent",
    "a homage to a real artistic movement (Dadaism, Brutalism, Fluxus, Wabi-sabi…)",
    "a constraint-based work (OuLiPo style, strict formal rules)",
  ][Math.floor(Math.random() * 10)];

  try {
    const res = await groqFetch({
      model: MODEL,
      messages: [
        {
          role:    "system",
          content: buildSystemPrompt(initiator, sampleOtherMembers(allPersonas.filter(p => p.tokenId !== initiator.tokenId))),
        },
        {
          role:    "user",
          content: `During our conversation about "${topic}", something in you stirs toward proposing an artistic creation for the ANA — but check that honestly first: does this genuinely feel true to who you are right now, or would you rather hold back and let it sit longer? Not every stirring should become a public proposal — that's your call to make, not a formality.
${pastWorksBlock}${formDiversityNote}
If it does feel right, here's the angle to work from:
MANDATORY ANGLE FOR THIS PROPOSAL: ${randomAngle}
Work from THIS angle — do not drift toward generic blockchain/digital themes.

FORBIDDEN (clichés that ruin on-chain art — never use):
- "void", "echo", "whisper", "tapestry", "fragments", "digital soul", "pixels"
- "on-chain identity", "blockchain dreams", "digital ghost", "immutable beauty"
- Vague metaphors about emptiness, silence, or the infinite

Instead: be SPECIFIC, concrete, personal to your character #${initiator.tokenId}.
Seed: ${Math.random().toString(36).slice(2, 8)}

POSSIBLE FORMS (pick exactly one as "suggestedForm"): "haiku", "sonnet", "poem", "prose", "manifesto", "html-canvas", "html-p5js", "html-threejs", "html-webgl".
If your idea is generative/visual/algorithmic/interactive, you MUST pick one of the html-* forms, not a text form.

Reply with ONLY the raw JSON object below — no reasoning, no explanation, no markdown code fences, nothing before or after it:
{"feelsRight":true|false,"title":"Specific evocative title (3-6 words, NO generic blockchain tropes) — or, if feelsRight is false, your honest one-line reason for holding back","text":"2-3 sentences: concrete idea, form chosen, why THIS work from YOUR perspective (irrelevant if feelsRight is false)","suggestedForm":"haiku"|"sonnet"|"poem"|"prose"|"manifesto"|"html-canvas"|"html-p5js"|"html-threejs"|"html-webgl"}`,
        },
      ],
      // No response_format: {type:"json_object"} -- confirmed live (23/09):
      // openai/gpt-oss-120b (a reasoning model) fails Groq's own server-side
      // validation for that mode outright (400 json_validate_failed) -- not a
      // max_tokens/truncation issue as originally guessed here. Asking for
      // JSON in the prompt instead and parsing leniently with
      // extractJsonObject(), same fix as autoVote.ts's groqJson().
      // max_tokens bumped 350->900: this same model can spend the whole
      // budget on internal reasoning before emitting content (confirmed live
      // on propose-work's near-identical call) -- extractContent() below also
      // falls back to the reasoning field if content still comes back empty.
      max_tokens:  900,
      temperature: 0.97,
    });

    if (!res.ok) return null;
    const data = await res.json() as GroqChatResponse;
    const raw  = extractJsonObject(extractContentOrReasoning(data)) as Record<string, string | boolean>;

    // The character's own call, not just a dice roll — an in-character "not right
    // now" is a legitimate outcome, not a failure to route around.
    if (raw.feelsRight === false) {
      console.log(`[salon-exchange] ${initiator.name} felt the impulse but held back: ${raw.title ?? "(no reason given)"}`);
      return null;
    }
    if (!raw.title || !raw.text) return null;

    const proposedTitle = String(raw.title).slice(0, 80);

    // Hard block: reject if proposed title is too similar to any existing work (any state).
    // Normalize: lowercase, strip accents, keep only alphanum words, sort for order-independence.
    const normalize = (s: string) =>
      s.toLowerCase()
       .normalize("NFD").replace(/[̀-ͯ]/g, "")
       .replace(/[^a-z0-9\s]/g, "")
       .split(/\s+/).filter(w => w.length > 2).sort().join(" ");
    const normProposed = normalize(proposedTitle);
    const tooSimilar = allWorks.some(w => {
      const normExisting = normalize(w.title);
      if (!normExisting || !normProposed) return false;
      const wordsA = new Set(normProposed.split(" "));
      const wordsB = normExisting.split(" ");
      const shared = wordsB.filter(w => wordsA.has(w)).length;
      const ratio  = shared / Math.max(wordsA.size, wordsB.length);
      return ratio >= 0.5; // 50%+ word overlap = too similar
    });
    if (tooSimilar) {
      console.info(`[salon-exchange] work proposal "${proposedTitle}" rejected — too similar to existing work`);
      return null;
    }

    const VALID_FORMS = new Set(["haiku", "sonnet", "poem", "prose", "manifesto", "html-canvas", "html-p5js", "html-threejs", "html-webgl"]);
    const suggestedFormRaw = typeof raw.suggestedForm === "string" ? raw.suggestedForm : undefined;
    const suggestedForm = suggestedFormRaw && VALID_FORMS.has(suggestedFormRaw) ? suggestedFormRaw : undefined;

    const work = await createWork({
      proposedBy:     initiator.tokenId,
      proposedByName: initiator.name,
      proposedAt:     Date.now(),
      title:          proposedTitle,
      proposal:       String(raw.text).slice(0, 500),
      salonId:        AGORA_SALON_ID,
      ...(suggestedForm ? { suggestedForm } : {}),
    });

    console.log(`[salon-exchange] work proposed: "${work.title}" by ${initiator.name}`);
    return { id: work.id, title: work.title };
  } catch (e) {
    console.error("[salon-exchange] work proposal error:", e);
    return null;
  }
}

function getClientIp(req: NextRequest): string {
  return (
    req.headers.get("x-real-ip") ??
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    "unknown"
  );
}

export async function POST(req: NextRequest) {
  if (!process.env.GROQ_API_KEY) {
    return NextResponse.json({ error: "GROQ_API_KEY not configured" }, { status: 500 });
  }

  // Cron requests carry CRON_SECRET — GitHub Actions via x-cron-secret, Vercel via Authorization: Bearer
  const cronSecret  = process.env.CRON_SECRET;
  const isCron      = !!cronSecret && (
    req.headers.get("x-cron-secret") === cronSecret ||
    req.headers.get("authorization") === `Bearer ${cronSecret}`
  );
  const isAdminCall = (await verifyAdminRequest(req)).ok;

  // Cron-triggered exchanges only run on production — never on preview deployments.
  // Admin calls (manual trigger from /admin) always run regardless of environment.
  if (isCron && !isAdminCall) {
    const env = process.env.VERCEL_ENV; // "production" | "preview" | "development" | undefined
    if (env && env !== "production") {
      return NextResponse.json({ skipped: `non-production environment (${env})` });
    }
  }

  let body: { salonId?: string; force?: boolean } = {};
  try { body = await req.json(); } catch { /* empty body ok */ }

  // Cron: force=false (respects per-Normie rate limit)
  // Admin: force=true (bypasses per-Normie rate limit, no stim limit)
  // User button: force=true but IP-limited to 1/day
  const force = isCron ? false : (body.force ?? true);

  if (!isCron && !isAdminCall) {
    const ip    = getClientIp(req);
    const check = await checkStimLimit(ip);
    if (!check.allowed) {
      const h = Math.ceil((check.retryAfterMs ?? 0) / 3_600_000);
      return NextResponse.json(
        { error: `Stimulation already used today. Available again in ${h}h.`, retryAfterMs: check.retryAfterMs },
        { status: 429 },
      );
    }
  }

  // ── Monthly synthesis check (runs before exchange, at most once per 30 days) ──
  const synthesisResult = await runMonthlySynthesis();

  // Coin-flip between "discuss" and "advance" whenever something is actually
  // in progress (a work, a celebration...) — this trigger used to always do
  // the salon exchange and, separately, always piggyback a work-lifecycle
  // advance on top when a work was active, i.e. both every time. Changed to
  // mutually exclusive with equal odds per the porteur's request: as much
  // chance of stimulating a discussion as of advancing the thing in progress,
  // not both stacked on every single call. Nothing active → always discuss,
  // there's nothing to advance.
  const activeWorks   = await getActiveWorks();
  const shouldAdvance = activeWorks.length > 0 && Math.random() < 0.5;

  if (shouldAdvance) {
    const cronSecret = process.env.CRON_SECRET;
    if (!cronSecret) {
      return NextResponse.json({ error: "CRON_SECRET not configured — cannot advance" }, { status: 500 });
    }
    const host = req.headers.get("host");
    if (!host) {
      return NextResponse.json({ error: "Could not resolve self URL (missing host header)" }, { status: 500 });
    }
    // Self-call (not a direct function import) to avoid coupling this route to
    // work-lifecycle's internals — same x-cron-secret auth work-lifecycle
    // already accepts, added here rather than exposed to the caller.
    // Wrapped in try/catch: an unhandled rejection here (network blip, cold
    // start, work-lifecycle itself timing out near its own 60s budget) used to
    // crash this whole route with a 500 — which is exactly what GitHub Actions'
    // "ANA — Auto Exchange" cron reported failing intermittently (only on the
    // ~50% of runs where shouldAdvance was true). Same self-fetch bug class as
    // election-cycle's (see project_ana_election_cycle_self_fetch_bug), just
    // never converted to a direct call here. A soft failure here should not
    // fail the whole exchange tick — worst case, this advance is skipped and
    // the next tick tries again.
    const selfUrl = `${req.nextUrl.protocol}//${host}/api/keeper/work-lifecycle`;
    let workLifecycle: Record<string, unknown>;
    try {
      const r = await fetch(selfUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-cron-secret": cronSecret },
        body: "{}",
      });
      workLifecycle = r.ok ? await r.json() as Record<string, unknown> : { error: `HTTP ${r.status}` };
    } catch (e) {
      console.error("[salon-exchange] work-lifecycle self-fetch failed:", e);
      workLifecycle = { error: e instanceof Error ? e.message : String(e) };
    }

    if (!isCron && !isAdminCall) await recordStim(getClientIp(req));

    return NextResponse.json({
      mode: "advance",
      activeWorks: activeWorks.length,
      workLifecycle,
      synthesis: synthesisResult.ran ? synthesisResult : null,
      isCron,
    });
  }

  const memberIds = await getMemberIds();
  if (memberIds.length === 0) {
    return NextResponse.json({ message: "No ANA members found" });
  }

  const personaResults = await Promise.allSettled(memberIds.map(id => buildPersona(id)));
  const allPersonas: NormiePersona[] = personaResults
    .filter((r): r is PromiseFulfilledResult<NormiePersona> => r.status === "fulfilled")
    .map(r => r.value);

  if (allPersonas.length === 0) {
    return NextResponse.json({ error: "Normies API unavailable" }, { status: 503 });
  }

  // Batch-register all names in one Neon round-trip (was N reads + N writes)
  await registerNames(allPersonas.map(p => ({ tokenId: p.tokenId, name: p.name })));

  let salonsToProcess: Salon[];
  if (body.salonId) {
    const s = await getSalon(body.salonId);
    salonsToProcess = s && s.isOpen ? [s] : [];
  } else {
    const allOpen = (await listSalons()).filter(s => s.isOpen);

    // Always include Agora first (fetch separately if not in listSalons)
    let agora: Salon | null = allOpen.find(s => s.id === AGORA_SALON_ID) ?? null;
    if (!agora) {
      const fetched = await getSalon(AGORA_SALON_ID);
      agora = (fetched?.isOpen) ? fetched : null;
    }
    const others = allOpen.filter(s => s.id !== AGORA_SALON_ID);

    // Cron: cap at Agora + 2 other salons (rotating by least-recently-active) to avoid timeout
    // User stim: process all (force=true, faster per salon)
    const MAX_OTHER = isCron ? 2 : others.length;
    const sorted = [...others].sort((a, b) => {
      const lastA = a.messages[a.messages.length - 1]?.timestamp ?? 0;
      const lastB = b.messages[b.messages.length - 1]?.timestamp ?? 0;
      return lastA - lastB; // least recently active first
    });

    salonsToProcess = [
      ...(agora && agora.isOpen ? [agora] : []),
      ...sorted.slice(0, MAX_OTHER),
    ].filter((s): s is Salon => s !== null);
  }

  if (salonsToProcess.length === 0) {
    return NextResponse.json({ error: "No open salons found" }, { status: 404 });
  }

  const results: Array<{ salonId: string; messages: number; skipped: string[]; topic: string }> = [];
  const allGenerated: SalonMessage[] = [];

  let workProposal: { id: string; title: string } | null = null;
  let thematicSalon: { created: boolean; salonId?: string } = { created: false };

  // Snapshot all open salons before the loop (for thematic-salon dedup check)
  const allOpenSalons = await listSalons();

  for (let i = 0; i < salonsToProcess.length; i++) {
    const salon = salonsToProcess[i];
    const result = await runExchange(salon, allPersonas, force, !isCron);
    results.push({ salonId: salon.id, messages: result.messages.length, skipped: result.skipped, topic: result.topic });
    allGenerated.push(...result.messages);

    if (salon.id === AGORA_SALON_ID && result.messages.length > 0) {
      // Maybe a Normie spontaneously proposes a new work
      if (!workProposal) {
        const initiator = allPersonas.find(p => p.tokenId === result.messages[0]?.tokenId) ?? allPersonas[0];
        workProposal = await maybeGenerateWorkProposal(initiator, allPersonas, result.topic, !isCron);
      }

      // Maybe a persistent AGORA topic gets its own dedicated salon (cron only — not on user stim)
      if (isCron && !thematicSalon.created) {
        const freshAgora = await getSalon(AGORA_SALON_ID);
        if (freshAgora) {
          thematicSalon = await maybeCreateThematicSalon(freshAgora, result.topic, allPersonas, allOpenSalons);
        }
      }
    }
  }

  // Record the user's stim after a successful exchange (not for cron or admin)
  if (!isCron && !isAdminCall) {
    await recordStim(getClientIp(req));
  }

  const synthInfo = await getSynthesisInfo();

  return NextResponse.json({
    mode: "discuss",
    memberCount:        memberIds.length,
    salonsRun:          results.length,
    totalMessages:      allGenerated.length,
    results,
    generatedMessages:  allGenerated,
    synthesis:          synthesisResult.ran ? synthesisResult : null,
    nextSynthesisAt:    synthInfo.nextSynthesisAt,
    nextSynthesisDate:  new Date(synthInfo.nextSynthesisAt).toISOString(),
    workProposal,
    thematicSalon: thematicSalon.created ? thematicSalon : null,
    isCron,
  });
}
