export const NormieCollectionAbi = [
  {
    inputs: [
      { internalType: "address", name: "to",      type: "address" },
      { internalType: "string",  name: "content", type: "string"  },
      { internalType: "string",  name: "title",   type: "string"  },
    ],
    name:            "mint",
    outputs:         [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type:            "function",
  },
  {
    inputs:          [],
    name:            "minter",
    outputs:         [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type:            "function",
  },
  {
    inputs:          [{ internalType: "address", name: "newMinter", type: "address" }],
    name:            "setMinter",
    outputs:         [],
    stateMutability: "nonpayable",
    type:            "function",
  },
  {
    inputs:          [],
    name:            "nextTokenId",
    outputs:         [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type:            "function",
  },
  {
    inputs:          [],
    name:            "creatorNormieTokenId",
    outputs:         [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type:            "function",
  },
  {
    inputs:  [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name:    "getTokenData",
    outputs: [{
      components: [
        { internalType: "string",  name: "content",   type: "string"  },
        { internalType: "string",  name: "title",     type: "string"  },
        { internalType: "uint256", name: "createdAt", type: "uint256" },
      ],
      internalType: "struct NormieCollection.TokenData",
      name:         "",
      type:         "tuple",
    }],
    stateMutability: "view",
    type:            "function",
  },
  {
    inputs:  [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name:    "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type:            "function",
  },
  {
    anonymous: false,
    inputs:    [
      { indexed: true,  internalType: "uint256", name: "tokenId",   type: "uint256" },
      { indexed: false, internalType: "string",  name: "title",     type: "string"  },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "TokenMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs:    [{ indexed: true, internalType: "address", name: "newMinter", type: "address" }],
    name:      "MinterUpdated",
    type:      "event",
  },
] as const;
